/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* $Id$ */

package org.docx4j.fop.wordlayout;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.ListIterator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.apache.fop.layoutmgr.inline.*;
import org.apache.fop.layoutmgr.inline.LineLayoutManager.LineBreakPosition;

import org.apache.fop.area.Area;
import org.apache.fop.area.LineArea;
import org.apache.fop.area.Trait;
import org.apache.fop.area.inline.InlineArea;
import org.apache.fop.complexscripts.bidi.BidiResolver;
import org.apache.fop.datatypes.Length;
import org.apache.fop.datatypes.Numeric;
import org.apache.fop.fo.Constants;
import org.apache.fop.fo.flow.Block;
import org.apache.fop.fo.properties.CommonHyphenation;
import org.apache.fop.fo.properties.KeepProperty;
import org.apache.fop.fonts.Font;
import org.apache.fop.fonts.FontInfo;
import org.apache.fop.fonts.FontTriplet;
import org.apache.fop.hyphenation.Hyphenation;
import org.apache.fop.hyphenation.Hyphenator;
import org.apache.fop.layoutmgr.Adjustment;
import org.apache.fop.layoutmgr.BlockLayoutManager;
import org.apache.fop.layoutmgr.BlockLevelLayoutManager;
import org.apache.fop.layoutmgr.BreakElement;
import org.apache.fop.layoutmgr.BreakingAlgorithm;
import org.apache.fop.layoutmgr.ElementListObserver;
import org.apache.fop.layoutmgr.FloatContentLayoutManager;
import org.apache.fop.layoutmgr.FootenoteUtil;
import org.apache.fop.layoutmgr.FootnoteBodyLayoutManager;
import org.apache.fop.layoutmgr.InlineKnuthSequence;
import org.apache.fop.layoutmgr.Keep;
import org.apache.fop.layoutmgr.KnuthBlockBox;
import org.apache.fop.layoutmgr.KnuthBox;
import org.apache.fop.layoutmgr.KnuthElement;
import org.apache.fop.layoutmgr.KnuthGlue;
import org.apache.fop.layoutmgr.KnuthPenalty;
import org.apache.fop.layoutmgr.KnuthPossPosIter;
import org.apache.fop.layoutmgr.KnuthSequence;
import org.apache.fop.layoutmgr.LayoutContext;
import org.apache.fop.layoutmgr.LayoutManager;
import org.apache.fop.layoutmgr.LeafPosition;
import org.apache.fop.layoutmgr.inline.KnuthInlineBox;
import org.apache.fop.layoutmgr.ListElement;
import org.apache.fop.layoutmgr.NonLeafPosition;
import org.apache.fop.layoutmgr.Position;
import org.apache.fop.layoutmgr.PositionIterator;
import org.apache.fop.layoutmgr.SpaceSpecifier;
import org.apache.fop.traits.MinOptMax;

/**
 * docx4j's copy of FOP 2.11's LineLayoutManager with Word's greedy line breaking
 * (CR-001 Phase 5); see the package documentation.  Apart from
 * findOptimalBreakingPoints and the greedy members of LineBreakingAlgorithm,
 * the code is FOP's (Apache License 2.0), mechanically adapted: it extends
 * LineLayoutManager so the rest of FOP treats it as one, keeps its own state,
 * and reaches LineBreakPosition's package-private constructor and private
 * fields through LBP.
 *
 * Original: LayoutManager for lines. It builds one or more lines containing
 * inline areas generated by its sub layout managers.
 * A break is found for each line which may contain one of more
 * breaks from the child layout managers.
 * Once a break is found then it is return for the parent layout
 * manager to handle.
 * When the areas are being added to the page this manager
 * creates a line area to contain the inline areas added by the
 * child layout managers.
 */
public class WordLineLayoutManager extends LineLayoutManager {

    /**
     * this constant is used to create elements when text-align is center:
     * every TextLM descendant of LineLM must use the same value,
     * otherwise the line breaking algorithm does not find the right
     * break point
     */
    public static final int DEFAULT_SPACE_WIDTH = 3336;

    /**
     * logging instance
     */
    private static final Logger log = LoggerFactory.getLogger(WordLineLayoutManager.class);

    private final Block fobj;
    private boolean isFirstInBlock;

    /**
     * Private class to store information about inline breaks.
     * Each value holds the start and end indexes into a List of
     * inline break positions.
     */
    // LineBreakPosition: the superclass's nested class is used; see LBP for access.

    private int bidiLevel = -1;
    private int textAlignment = EN_JUSTIFY;
    private int textAlignmentLast;
    private int effectiveAlignment;
    private Length textIndent;
    private Length lastLineEndIndent;
    private CommonHyphenation hyphenationProperties;
    private Numeric hyphenationLadderCount;
    private int wrapOption = EN_WRAP;
    private int whiteSpaceTreament;
    //private LayoutProps layoutProps;

    private final Length lineHeight;
    private final int lead;
    private final int follow;
    private AlignmentContext alignmentContext;

    private int baselineOffset = -1;

    private List<KnuthSequence> knuthParagraphs;

    private LineLayoutPossibilities lineLayouts;
    private LineLayoutPossibilities[] lineLayoutsList;
    private int ipd;
    /**
     * When layout must be re-started due to a change of IPD, there is no need
     * to perform hyphenation on the remaining Knuth sequence once again.
     */
    private boolean hyphenationPerformed;

    /**
     * This class is used to remember
     * which was the first element in the paragraph
     * returned by each LM.
     */
    private final class Update {
        private final InlineLevelLayoutManager inlineLM;
        private final int firstIndex;

        private Update(InlineLevelLayoutManager lm, int index) {
            inlineLM = lm;
            firstIndex = index;
        }
    }

    // this class represents a paragraph
    private static class Paragraph extends InlineKnuthSequence {

        private static final long serialVersionUID = 5862072380375189105L;

        /** Number of elements to ignore at the beginning of the list. */
        private int ignoreAtStart;
        /** Number of elements to ignore at the end of the list. */
        private int ignoreAtEnd;

        // space at the end of the last line (in millipoints)
        private MinOptMax lineFiller;
        private final int textAlignment;
        private final int textAlignmentLast;
        private final int textIndent;
        private final int lastLineEndIndent;
        // the LM which created the paragraph
        private final WordLineLayoutManager layoutManager;

        Paragraph(WordLineLayoutManager llm, int alignment, int alignmentLast,
                         int indent, int endIndent) {
            super();
            layoutManager = llm;
            textAlignment = alignment;
            textAlignmentLast = alignmentLast;
            textIndent = indent;
            lastLineEndIndent = endIndent;
        }

        @Override
        public void startSequence() {
            // set the minimum amount of empty space at the end of the
            // last line
            if (textAlignment == EN_CENTER) {
                lineFiller = MinOptMax.getInstance(lastLineEndIndent);
            } else {
                lineFiller = MinOptMax.getInstance(lastLineEndIndent, lastLineEndIndent,
                        layoutManager.ipd);
            }

            // add auxiliary elements at the beginning of the paragraph
            if (textAlignment == EN_CENTER && textAlignmentLast != EN_JUSTIFY) {
                this.add(new KnuthGlue(0, 3 * DEFAULT_SPACE_WIDTH, 0,
                                       null, false));
                ignoreAtStart++;
            }

            // add the element representing text indentation
            // at the beginning of the first paragraph
            if (layoutManager.isFirstInBlock && layoutManager.knuthParagraphs.size() == 0
                        && textIndent != 0) {
                this.add(new KnuthInlineBox(textIndent, null,
                                      null, false));
                ignoreAtStart++;
            }
        }

        public void endParagraph() {
            KnuthSequence finishedPar = this.endSequence();
            if (finishedPar != null) {
                layoutManager.knuthParagraphs.add(finishedPar);
            }
        }

        @Override
        public KnuthSequence endSequence() {
            if (this.size() > ignoreAtStart) {
                if (textAlignment == EN_CENTER
                    && textAlignmentLast != EN_JUSTIFY) {
                    this.add(new KnuthGlue(0, 3 * DEFAULT_SPACE_WIDTH, 0,
                                           null, false));
                    this.add(new KnuthPenalty(lineFiller.getOpt(), -KnuthElement.INFINITE,
                                              false, null, false));
                    ignoreAtEnd = 2;
                } else if (textAlignmentLast != EN_JUSTIFY) {
                    // add the elements representing the space
                    // at the end of the last line
                    // and the forced break
                    this.add(new KnuthPenalty(0, KnuthElement.INFINITE,
                                              false, null, false));
                    this.add(new KnuthGlue(0,
                            lineFiller.getStretch(),
                            lineFiller.getShrink(), null, false));
                    this.add(new KnuthPenalty(lineFiller.getOpt(), -KnuthElement.INFINITE,
                                              false, null, false));
                    ignoreAtEnd = 3;
                } else {
                    // add only the element representing the forced break
                    this.add(new KnuthPenalty(lineFiller.getOpt(), -KnuthElement.INFINITE,
                                              false, null, false));
                    ignoreAtEnd = 1;
                }
                return this;
            } else {
                this.clear();
                return null;
            }
        }

        /**
         * @return true if the sequence contains a box
         */
        public boolean containsBox() {
            for (Object o : this) {
                KnuthElement el = (KnuthElement) o;
                if (el.isBox()) {
                    return true;
                }
            }
            return false;
        }
    }

    private class LineBreakingAlgorithm extends BreakingAlgorithm {
        private final LineLayoutManager thisLLM;
        private final int pageAlignment;
        private int activePossibility;
        private int addedPositions;
        private final int textIndent;
        private final int lineHeight;
        private final int lead;
        private final int follow;
        private static final double MAX_DEMERITS = 10e6;

        public LineBreakingAlgorithm(int pageAlign, int textAlign, int textAlignLast, int indent, int fillerWidth,
                int lh, int ld, int fl, boolean first, int maxFlagCount, LineLayoutManager llm) {
            super(textAlign, textAlignLast, first, false, maxFlagCount);
            pageAlignment = pageAlign;
            textIndent = indent;
            lineHeight = lh;
            lead = ld;
            follow = fl;
            thisLLM = llm;
            activePossibility = -1;
        }

        // ---- Word-style greedy (first-fit) line breaking ------------------------

        /** The single active node: the last committed break. */
        private KnuthNode active;
        /** The last legal break at which the line still fitted, and the totals then. */
        private int candIdx = -1;
        private int candDifference;
        private double candRatio;
        private int candShrink;
        private int candStretch;
        private int candTotalWidth;
        private int candTotalStretch;
        private int candTotalShrink;
        private boolean restartRequested;

        @Override
        public int findBreakingPoints(KnuthSequence par, int startIndex,
                                      double threshold, boolean force, int allowedBreaks) {
            this.par = par;
            initialize();
            boolean previousIsBox = false;
            int previousPosition = startIndex;
            if (alignment != Constants.EN_CENTER) {
                int firstBoxIndex = startIndex;
                while (firstBoxIndex < par.size() && !((KnuthElement) par.get(firstBoxIndex)).isBox()) {
                    firstBoxIndex++;
                }
                previousPosition = (firstBoxIndex >= par.size()) ? startIndex : firstBoxIndex - 1;
            }
            previousPosition = Math.max(0, previousPosition);
            active = createNode(previousPosition, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, null);
            addNode(0, active);
            candIdx = -1;
            restartRequested = false;
            if (WordLineLayoutManager.log.isTraceEnabled()) {
                StringBuilder sb = new StringBuilder("greedy paragraph, " + par.size() + " elements, lineWidth=" + getLineWidth() + ":");
                for (int i = 0; i < par.size(); i++) {
                    KnuthElement e = (KnuthElement) par.get(i);
                    sb.append("\n  [").append(i).append("] ").append(e.isBox() ? "box " : e.isGlue() ? "glue " : "pen ")
                      .append("w=").append(e.getWidth());
                    if (e.isGlue()) sb.append(" st=").append(e.getStretch()).append(" sh=").append(e.getShrink());
                    if (e.isPenalty()) sb.append(" p=").append(e.getPenalty()).append(e.isForcedBreak() ? " FORCED" : "");
                    if (e.isAuxiliary()) sb.append(" aux");
                }
                WordLineLayoutManager.log.trace(sb.toString());
            }
            for (int elementIndex = startIndex; elementIndex < par.size(); elementIndex++) {
                previousIsBox = handleElementAt(elementIndex, previousIsBox, allowedBreaks).isBox();
                if (restartRequested) {
                    restartRequested = false;
                    elementIndex = restartFrom(active, elementIndex);
                }
            }
            finish();
            KnuthNode last = active;
            updateData1(last.line, last.totalDemerits);
            greedyBreakPoints(last, par, last.line);
            activeLines = null;
            return last.line;
        }

        /** As BreakingAlgorithm.calculateBreakPoints: from the last line backwards,
         *  which is the order LineLayoutPossibilities.addBreakPosition expects. */
        private void greedyBreakPoints(KnuthNode node, KnuthSequence par, int total) {
            KnuthNode n = node;
            for (int i = node.line; i > 0; i--) {
                updateData2(n, par, total);
                n = n.previous;
            }
        }

        @Override
        protected void considerLegalBreak(KnuthElement element, int elementIdx) {
            if (active == null || active.position == elementIdx) {
                return;
            }
            int difference = computeDifference(active, element, elementIdx);
            if (!elementCanEndLine(element, endLine, difference)) {
                return;
            }
            double r = computeAdjustmentRatio(active, difference);
            int availableShrink = totalShrink - active.totalShrink;
            int availableStretch = totalStretch - active.totalStretch;
            if (WordLineLayoutManager.log.isTraceEnabled()) {
                WordLineLayoutManager.log.trace("greedy idx=" + elementIdx + " diff=" + difference + " lineWidth=" + getLineWidth()
                        + " active.pos=" + active.position + " cand=" + candIdx + " forced=" + element.isForcedBreak()
                        + " align=" + alignment + " justify=" + Constants.EN_JUSTIFY + " maxShrink=" + WordLayoutCustomizer.maxSpaceShrink()
                        + " el=" + element);
            }
            boolean fits = difference >= 0 || fitsByShrinkingSpaces(elementIdx, difference);
            if (!fits && candIdx > active.position) {
                // too long now (whether or not this is the paragraph's own forced break):
                // break at the last break that fitted and rescan from there; a forced
                // break is met again after the rescan
                commit(candIdx, candDifference, candRatio, candShrink, candStretch,
                        candTotalWidth, candTotalStretch, candTotalShrink, true);
                return;
            }
            if (element.isForcedBreak()) {
                commit(elementIdx, difference, r, availableShrink, availableStretch,
                        totalWidth, totalStretch, totalShrink, false);
                return;
            }
            if (fits) {
                // fits at its natural width, or (justified) with the spaces compressed
                // within Word's limit: remember, keep going
                candIdx = elementIdx;
                candDifference = difference;
                candRatio = r;
                candShrink = availableShrink;
                candStretch = availableStretch;
                candTotalWidth = totalWidth;
                candTotalStretch = totalStretch;
                candTotalShrink = totalShrink;
                return;
            }
            // nothing fitted since the last break: an overlong word; break here, overfull
            commit(elementIdx, difference, r, availableShrink, availableStretch,
                    totalWidth, totalStretch, totalShrink, false);
        }

        /**
         * Word compresses the spaces of a justified line to pull in a word that does
         * not fit at natural width (measured, Word 365: glyphs keep their width, the
         * gaps go down to about 71-80% of the space width, depending on the font).
         * The limit is a fraction of the natural width of the line's spaces, set by
         * WordLayoutCustomizer.maxSpaceShrink (default 0.24).
         */
        private boolean fitsByShrinkingSpaces(int elementIdx, int difference) {
            if (alignment != Constants.EN_JUSTIFY || difference >= 0) {
                return difference >= 0;
            }
            double maxShrink = WordLayoutCustomizer.maxSpaceShrink();
            if (maxShrink <= 0) {
                return false;
            }
            int spaces = 0;
            for (int i = active.position + 1; i < elementIdx; i++) {
                KnuthElement e = getElement(i);
                if (e.isGlue() && e.getWidth() > 0) {
                    spaces += e.getWidth();
                }
            }
            return -difference <= maxShrink * spaces;
        }

        private void commit(int idx, int difference, double r, int availableShrink, int availableStretch,
                int tw, int ts, int tsh, boolean restart) {
            int fitness = r < -0.5 ? 0 : (r <= 0.5 ? 1 : (r <= 1 ? 2 : 3));
            KnuthNode node = createNode(idx, active.line + 1, fitness, tw, ts, tsh,
                    r, availableShrink, availableStretch, difference, 0, active);
            removeNode(active.line, active);
            active = node;
            candIdx = -1;
            if (restart) {
                restartRequested = true; // restartFrom() re-adds the node and resets the totals
            } else {
                addNode(node.line, node);
            }
        }

        @Override
        public void updateData1(int lineCount, double demerits) {
            lineLayouts.addPossibility(lineCount, demerits);
            if (WordLineLayoutManager.log.isTraceEnabled()) {
                WordLineLayoutManager.log.trace("Layout possibility in " + lineCount + " lines; break at position:");
            }
        }

        @Override
        public void updateData2(KnuthNode bestActiveNode,
                                KnuthSequence par,
                                int total) {
            // compute indent and adjustment ratio, according to
            // the value of text-align and text-align-last
            int startIndent;
            int endIndent;
            int difference = bestActiveNode.difference;
            int textAlign = (bestActiveNode.line < total) ? alignment : alignmentLast;

            switch (textAlign) {
            case Constants.EN_START:
                startIndent = 0;
                endIndent = difference > 0 ? difference : 0;
                break;
            case Constants.EN_END:
                startIndent = difference;
                endIndent = 0;
                break;
            case Constants.EN_CENTER:
                startIndent = difference / 2;
                endIndent = startIndent;
                break;
            default:
            case Constants.EN_JUSTIFY:
                startIndent = 0;
                endIndent = 0;
                break;
            }

            /*
            startIndent += (textAlign == Constants.EN_CENTER)
                      ? difference / 2 : (textAlign == Constants.EN_END) ? difference : 0;
            */
            startIndent += (bestActiveNode.line == 1 && indentFirstPart && isFirstInBlock)
                      ? textIndent : 0;

            double ratio = (textAlign == Constants.EN_JUSTIFY
                || difference < 0 && -difference <= bestActiveNode.availableShrink)
                        ? bestActiveNode.adjustRatio : 0;

            // add nodes at the beginning of the list, as they are found
            // backwards, from the last one to the first one

            // the first time this method is called, initialize activePossibility
            if (activePossibility == -1) {
                activePossibility = 0;
                addedPositions = 0;
            }

            if (addedPositions == lineLayouts.getLineCount(activePossibility)) {
                activePossibility++;
                addedPositions = 0;
            }

            int lack = difference + bestActiveNode.availableShrink;
            // if this LLM is nested inside a BlockContainerLayoutManager that is constraining
            // the available width and thus responsible for the overflow then we do not issue
            // warning event here and instead let the BCLM handle that at a later stage
            if (lack < 0 && !handleOverflow(-lack)) {
                InlineLevelEventProducer eventProducer
                    = InlineLevelEventProducer.Provider.get(
                        getFObj().getUserAgent().getEventBroadcaster());
                if (curChildLM.getFObj() == null) {
                    eventProducer.lineOverflows(this, getFObj().getName(), bestActiveNode.line,
                            -lack, getFObj().getLocator());
                } else {
                    eventProducer.lineOverflows(this, curChildLM.getFObj().getName(), bestActiveNode.line,
                        -lack, curChildLM.getFObj().getLocator());
                }
            }

            //WordLineLayoutManager.log.debug("LLM> (" + (lineLayouts.getLineNumber(activePossibility) - addedPositions)
            //    + ") difference = " + difference + " ratio = " + ratio);
            lineLayouts.addBreakPosition(makeLineBreakPosition(par,
                   (bestActiveNode.line > 1 ? bestActiveNode.previous.position + 1 : 0),
                   bestActiveNode.position,
                   bestActiveNode.availableShrink - (addedPositions > 0
                       ? 0 : ((Paragraph) par).lineFiller.getShrink()),
                   bestActiveNode.availableStretch,
                   difference, ratio, startIndent, endIndent), activePossibility);
            addedPositions++;
        }

        /* reset activePossibility, as if breakpoints have not yet been computed
         */
        public void resetAlgorithm() {
            activePossibility = -1;
        }

        private LineBreakPosition makeLineBreakPosition(KnuthSequence par, int firstElementIndex, int lastElementIndex,
                int availableShrink, int availableStretch, int difference, double ratio,
                int startIndent, int endIndent) {
            // line height calculation - spaceBefore may differ from spaceAfter
            // by 1mpt due to rounding
            int spaceBefore = (lineHeight - lead - follow) / 2;
            int spaceAfter = lineHeight - lead - follow - spaceBefore;
            // height before the main baseline
            int lineLead = lead;
            // maximum follow
            int lineFollow = follow;
            // true if this line contains only zero-height, auxiliary boxes
            // and the actual line width is 0; in this case, the line "collapses"
            // i.e. the line area will have bpd = 0
            boolean isZeroHeightLine = (difference == ipd);

            // if line-stacking-strategy is "font-height", the line height
            // is not affected by its content
            if (fobj.getLineStackingStrategy() != EN_FONT_HEIGHT) {
                ListIterator inlineIterator
                    = par.listIterator(firstElementIndex);
                AlignmentContext lastAC = null;
                int maxIgnoredHeight = 0; // See spec 7.13
                for (int j = firstElementIndex;
                     j <= lastElementIndex;
                     j++) {
                    KnuthElement element = (KnuthElement) inlineIterator.next();
                    if (element instanceof KnuthInlineBox) {
                        AlignmentContext ac = ((KnuthInlineBox) element).getAlignmentContext();
                        if (ac != null && lastAC != ac) {
                            if (!ac.usesInitialBaselineTable()
                                || ac.getAlignmentBaselineIdentifier() != EN_BEFORE_EDGE
                                   && ac.getAlignmentBaselineIdentifier() != EN_AFTER_EDGE) {
                                if (fobj.getLineHeightShiftAdjustment() == EN_CONSIDER_SHIFTS
                                    || ac.getBaselineShiftValue() == 0) {
                                    int alignmentOffset = ac.getTotalAlignmentBaselineOffset();
                                    if (alignmentOffset + ac.getAltitude() > lineLead) {
                                        lineLead = alignmentOffset + ac.getAltitude();
                                    }
                                    if (ac.getDepth() - alignmentOffset > lineFollow)  {
                                        lineFollow = ac.getDepth() - alignmentOffset;
                                    }
                                }
                            } else {
                                if (ac.getHeight() > maxIgnoredHeight) {
                                    maxIgnoredHeight = ac.getHeight();
                                }
                            }
                            lastAC = ac;
                        }
                        if (isZeroHeightLine
                            && (!element.isAuxiliary() || ac != null && ac.getHeight() > 0)) {
                            isZeroHeightLine = false;
                        }
                    }
                }

                if (lineFollow < maxIgnoredHeight - lineLead) {
                    lineFollow = maxIgnoredHeight - lineLead;
                }
            }

            constantLineHeight = lineLead + lineFollow;

            if (isZeroHeightLine) {
                return LBP.create(thisLLM,
                                             knuthParagraphs.indexOf(par),
                                             firstElementIndex, lastElementIndex,
                                             availableShrink, availableStretch,
                                             difference, ratio, 0, startIndent, endIndent,
                                             0, ipd, 0, 0, 0);
            } else if (wordLineBox > 0) {
                int[] line = wordLine(par, firstElementIndex, lastElementIndex);
                return LBP.create(thisLLM,
                                             knuthParagraphs.indexOf(par),
                                             firstElementIndex, lastElementIndex,
                                             availableShrink, availableStretch,
                                             difference, ratio, 0, startIndent, endIndent,
                                             line[0], ipd, 0, line[1], line[2]);
            } else {
                return LBP.create(thisLLM,
                                             knuthParagraphs.indexOf(par),
                                             firstElementIndex, lastElementIndex,
                                             availableShrink, availableStretch,
                                             difference, ratio, 0, startIndent, endIndent,
                                             lineLead + lineFollow,
                                             ipd, spaceBefore, spaceAfter,
                                             lineLead);
            }
        }

        /**
         * A line as Word makes it: {box height, extra leading below, baseline}, in
         * millipoints.  Word sizes a line from the runs on it: the ascent is the
         * largest run ascent (usWinAscent + external leading, at the run's size) and
         * the descent the largest run descent, whatever the run's vertical
         * alignment (a raised superscript still counts its full height, the shift
         * itself not).  The block carries those for its dominant run
         * (docx4j:line-box, docx4j:baseline); every other run's span carries Word's
         * pitch as its line-height, which FOP hands over as the alignment context's
         * height, split here in the block font's ascent:descent ratio (exact for the
         * same font at another size, within a few percent across fonts).  A box
         * whose bottom sits on the baseline (a picture) keeps FOP's altitude.
         * Then the spacing rule: "auto" multiplies the natural line by the block's
         * factor and puts the extra below as leading; "atLeast" puts any shortfall
         * above; "exact" clips to the given height.
         */
        private int[] wordLine(KnuthSequence par, int firstElementIndex, int lastElementIndex) {
            int blockAscent = wordBaseline > 0 ? wordBaseline : lead;
            int blockDescent = wordLineBox - blockAscent;
            double ratio = (double) blockAscent / wordLineBox;
            // from the runs on the line only: a line holding just a picture has no
            // descent in Word (its bottom is the picture's), text runs bring theirs
            int ascent = 0;
            int descent = 0;
            if (wordLineRule != RULE_EXACT && fobj.getLineStackingStrategy() != EN_FONT_HEIGHT) {
                ListIterator inlineIterator = par.listIterator(firstElementIndex);
                AlignmentContext lastAC = null;
                for (int j = firstElementIndex; j <= lastElementIndex; j++) {
                    KnuthElement element = (KnuthElement) inlineIterator.next();
                    if (!(element instanceof KnuthInlineBox)) continue;
                    AlignmentContext ac = ((KnuthInlineBox) element).getAlignmentContext();
                    if (ac == null || lastAC == ac) continue;
                    lastAC = ac;
                    if (ac.usesInitialBaselineTable()
                            && (ac.getAlignmentBaselineIdentifier() == EN_BEFORE_EDGE
                                || ac.getAlignmentBaselineIdentifier() == EN_AFTER_EDGE)) {
                        continue;
                    }
                    int h = ac.getHeight();
                    if (h <= 0) continue;
                    if (ac.getDepth() == 0) {
                        // bottom on the baseline (a picture): FOP's altitude is the height
                        ascent = Math.max(ascent, ac.getAltitude());
                        continue;
                    }
                    // Word's pitch for the run: its fo:inline's own line-height (docx4j puts
                    // Word's single-spacing pitch on every run's span); an inherited value
                    // is the block's line-height, in which case FOP's content height for
                    // the run is scaled by the block font's pitch : content ratio
                    int pitch = LBP.lineHeight(ac);
                    if (pitch <= 0 || pitch == lineHeight) {
                        pitch = (int) Math.round(h * (double) wordLineBox / (lead + follow));
                    }
                    // the run font's own ascent share when it can be read, else the block's
                    double r = ratio;
                    org.apache.fop.fonts.Font f = LBP.inlineFont(element.getLayoutManager());
                    if (f != null && f.getFontMetrics() != null) {
                        org.docx4j.fonts.PhysicalFont pf = org.docx4j.fonts.PhysicalFonts.get(f.getFontMetrics().getFullName());
                        org.docx4j.fonts.WordLineMetrics.Metrics m = pf == null ? null : org.docx4j.fonts.WordLineMetrics.get(pf);
                        if (m != null && !m.fallback && m.lineHeightFactor() > 0) {
                            r = (m.winAscent + m.externalLeading) / m.lineHeightFactor();
                        }
                    }
                    int alt = (int) Math.round(pitch * r);
                    if (WordLineLayoutManager.log.isDebugEnabled()) {
                        WordLineLayoutManager.log.debug("wordLine inline: fop height=" + h + " pitch=" + pitch + " ascent=" + alt
                                + " shift=" + ac.getBaselineShiftValue() + " font=" + (f == null ? "-" : f.getFontMetrics().getFullName() + "/" + f.getFontSize()));
                    }
                    ascent = Math.max(ascent, alt);
                    descent = Math.max(descent, pitch - alt);
                }
            }
            if (ascent + descent == 0) {
                // nothing measurable on the line (or exact spacing): the block's font
                ascent = blockAscent;
                descent = blockDescent;
            }
            if (WordLineLayoutManager.log.isDebugEnabled()) {
                WordLineLayoutManager.log.debug("wordLine: box=" + wordLineBox + " baseline=" + wordBaseline + " lineHeight=" + lineHeight
                        + " rule=" + wordLineRule + " -> ascent=" + ascent + " descent=" + descent);
            }
            int box, leading = 0, baseline;
            switch (wordLineRule) {
                case RULE_EXACT:
                    box = wordLineBox;
                    baseline = wordBaseline > 0 ? wordBaseline : lead;
                    break;
                case RULE_AT_LEAST:
                    box = Math.max(ascent + descent, lineHeight);
                    baseline = ascent + Math.max(0, lineHeight - (ascent + descent));
                    break;
                default:
                    box = ascent + descent;
                    baseline = ascent;
                    if (lineHeight > wordLineBox) {
                        double factor = (double) lineHeight / wordLineBox;
                        leading = (int) Math.round(box * factor) - box;
                    }
            }
            return new int[] { box, leading, baseline };
        }

        @Override
        protected int filterActiveNodes() {
            KnuthNode bestActiveNode = null;

            if (pageAlignment == EN_JUSTIFY) {
                // leave all active nodes and find the optimum line number
                //WordLineLayoutManager.log.debug("LBA.filterActiveNodes> " + activeNodeCount + " layouts");
                for (int i = startLine; i < endLine; i++) {
                    for (KnuthNode node = getNode(i); node != null; node = node.next) {
                        //WordLineLayoutManager.log.debug("                       + lines = "
                        //+ node.line + " demerits = " + node.totalDemerits);
                        bestActiveNode = compareNodes(bestActiveNode, node);
                    }
                }

                // scan the node set once again and remove some nodes
                //WordLineLayoutManager.log.debug("LBA.filterActiveList> layout selection");
                for (int i = startLine; i < endLine; i++) {
                    for (KnuthNode node = getNode(i); node != null; node = node.next) {
                        //if (Math.abs(node.line - bestActiveNode.line) > maxDiff) {
                        //if (false) {
                        if (node.line != bestActiveNode.line
                            && node.totalDemerits > MAX_DEMERITS) {
                            //WordLineLayoutManager.log.debug("                     XXX lines = "
                            //+ node.line + " demerits = " + node.totalDemerits);
                            removeNode(i, node);
                        } else {
                            //WordLineLayoutManager.log.debug("                      ok lines = "
                            //+ node.line + " demerits = " + node.totalDemerits);
                        }
                    }
                }
            } else {
                // leave only the active node with fewest total demerits
                for (int i = startLine; i < endLine; i++) {
                    for (KnuthNode node = getNode(i); node != null; node = node.next) {
                        bestActiveNode = compareNodes(bestActiveNode, node);
                        if (node != bestActiveNode) {
                            removeNode(i, node);
                        }
                    }
                }
            }
            return bestActiveNode.line;
        }
    }


    private int constantLineHeight = 12000;

    /**
     * Create a new Line Layout Manager.
     * This is used by the block layout manager to create
     * line managers for handling inline areas flowing into line areas.
     * @param block the block formatting object
     * @param lh the default line height
     * @param l the default lead, from top to baseline
     * @param f the default follow, from baseline to bottom
     */
    public WordLineLayoutManager(Block block, Length lh, int l, int f) {
        super(block, lh, l, f);
        fobj = block;
        // the child FObj are owned by the parent BlockLM
        // this LM has all its childLMs preloaded
        fobjIter = null;
        lineHeight = lh;
        lead = l;
        follow = f;
        wordLineBox = foreignLength(block, WordLayoutElementMapping.LINE_BOX);
        wordBaseline = foreignLength(block, WordLayoutElementMapping.BASELINE);
        String rule = foreignAttribute(block, WordLayoutElementMapping.LINE_RULE);
        wordLineRule = "exact".equals(rule) ? RULE_EXACT : "atLeast".equals(rule) ? RULE_AT_LEAST : RULE_AUTO;
    }

    private static final int RULE_AUTO = 0, RULE_EXACT = 1, RULE_AT_LEAST = 2;
    private final int wordLineRule;

    /**
     * Word's text box for a line of this paragraph and the baseline within it,
     * in millipoints, from the block's docx4j:line-box / docx4j:baseline
     * attributes ({@link WordLayoutElementMapping}); 0 when absent, in which
     * case lines are made as FOP makes them.  The block's line-height less the
     * box is the extra leading, emitted as {@link LeadingGlue} after each line
     * so that it is dropped at the bottom of a page, as Word drops it.
     */
    private final int wordLineBox;
    private final int wordBaseline;

    private static String foreignAttribute(Block block, String localName) {
        java.util.Map<?, ?> attrs = block.getForeignAttributes();
        if (attrs == null) return null;
        for (java.util.Map.Entry<?, ?> e : attrs.entrySet()) {
            org.apache.xmlgraphics.util.QName name = (org.apache.xmlgraphics.util.QName) e.getKey();
            if (WordLayoutElementMapping.URI.equals(name.getNamespaceURI())
                    && localName.equals(name.getLocalName())) {
                return String.valueOf(e.getValue()).trim();
            }
        }
        return null;
    }

    private static int foreignLength(Block block, String localName) {
        String v = foreignAttribute(block, localName);
        if (v == null) return 0;
        if (v.endsWith("pt")) v = v.substring(0, v.length() - 2);
        try {
            return (int) Math.round(Double.parseDouble(v) * 1000);
        } catch (NumberFormatException ex) {
            return 0;
        }
    }

    /** {@inheritDoc} */
    @Override
    public void initialize() {
        bidiLevel = fobj.getBidiLevel();
        textAlignment = fobj.getTextAlign();
        textAlignmentLast = fobj.getTextAlignLast();
        textIndent = fobj.getTextIndent();
        lastLineEndIndent = fobj.getLastLineEndIndent();
        hyphenationProperties = fobj.getCommonHyphenation();
        hyphenationLadderCount = fobj.getHyphenationLadderCount();
        wrapOption = fobj.getWrapOption();
        whiteSpaceTreament = fobj.getWhitespaceTreatment();
        //
        effectiveAlignment = getEffectiveAlignment(textAlignment, textAlignmentLast);
        isFirstInBlock = (this == getParent().getChildLMs().get(0));
    }

    private int getEffectiveAlignment(int alignment, int alignmentLast) {
        if (textAlignment != EN_JUSTIFY && textAlignmentLast == EN_JUSTIFY) {
            return 0;
        } else {
            return textAlignment;
        }
    }

    /** {@inheritDoc} */
    @Override
    public List<ListElement> getNextKnuthElements(LayoutContext context, int alignment) {
        if (alignmentContext == null) {
            FontInfo fi = fobj.getFOEventHandler().getFontInfo();
            FontTriplet[] fontkeys = fobj.getCommonFont().getFontState(fi);
            Font fs = fi.getFontInstance(fontkeys[0], fobj.getCommonFont().fontSize.getValue(this));
            alignmentContext = LBP.newAlignmentContext(fs, lineHeight.getValue(this),
                    context.getWritingMode());
        }
        context.setAlignmentContext(alignmentContext);
        ipd = context.getRefIPD();

        //PHASE 1: Create Knuth elements
        if (knuthParagraphs == null) {
            // it's the first time this method is called
            knuthParagraphs = new ArrayList<KnuthSequence>();

            // here starts Knuth's algorithm
            collectInlineKnuthElements(context);
        } else {
            // this method has been called before
            // all line breaks are already calculated
        }

        // return finished when there's no content
        if (knuthParagraphs.size() == 0) {
            setFinished(true);
            return null;
        }

        //PHASE 2: Create line breaks
        return createLineBreaks(context.getBPAlignment(), context);
    }

    /**
     * Get a sequence of KnuthElements representing the content
     * of the node assigned to the LM.
     * @param context   the LayoutContext used to store layout information
     * @param alignment the desired text alignment
     * @param restartPosition position at restart
     * @return the list of KnuthElements
     * @see LayoutManager#getNextKnuthElements(LayoutContext,int)
     */
    public List<ListElement> getNextKnuthElements(LayoutContext context, int alignment,
            LeafPosition restartPosition) {
        int parIndex = 0;
        int restartPositionIdx = 0;
        if (restartPosition != null) {
            WordLineLayoutManager.log.trace("Restarting line breaking from index " + restartPosition.getIndex());
            parIndex = restartPosition.getLeafPos();
            restartPositionIdx = restartPosition.getIndex();
        }

        for (int i = 0; i < parIndex; i++) {
            if (knuthParagraphs.size() > 1) {
                knuthParagraphs.remove(0);
            }
        }
        parIndex = 0;

        KnuthSequence paragraph = knuthParagraphs.get(parIndex);
        if (paragraph instanceof Paragraph) {
            ((Paragraph) paragraph).ignoreAtStart = 0;
            isFirstInBlock = false;
        }
        paragraph.subList(0, restartPositionIdx + 1).clear();
        Iterator<KnuthElement> iter = paragraph.iterator();
        while (iter.hasNext() && !iter.next().isBox()) {
            iter.remove();
        }
        if (!iter.hasNext()) {
            knuthParagraphs.remove(parIndex);
        }

        // return finished when there's no content
        if (knuthParagraphs.size() == 0) {
            setFinished(true);
            return null;
        }

        ipd = context.getRefIPD();
        //PHASE 2: Create line breaks
        return createLineBreaks(context.getBPAlignment(), context);
    }

    /**
     * Phase 1 of Knuth algorithm: Collect all inline Knuth elements before determining line breaks.
     * @param context the LayoutContext
     */
    /**
     * FOP 2.11's GlyphMapping.processWordMapping (the path taken for fonts with
     * GSUB or GPOS tables, so every embedded OpenType font while complex-script
     * features are on) never adds the letter spaces to a word's width, while the
     * renderer still spaces every glyph (TextArea's letter-space adjust); so
     * lines with letter-spacing overflow the margin (measured, CR-001 §6.6 item
     * 16: 3pt spacing, 95pt over; 0.25pt, one word too many).  The plain path,
     * processWordNoMapping, counts wordLength - 1 spaces plus one when a break
     * opportunity that is not a space follows.  That count is applied here to
     * each word box a text manager returned, the way its own path would have.
     */
    private void fixLetterSpaces(InlineLevelLayoutManager lm, List<KnuthSequence> seqs) {
        if (seqs == null) return;
        for (KnuthSequence seq : seqs) {
            for (int i = 0; i < seq.size(); i++) {
                Object o = seq.get(i);
                if (!(o instanceof KnuthInlineBox)) continue;
                KnuthInlineBox box = (KnuthInlineBox) o;
                // the child is usually an fo:inline's manager, whose elements wrap the
                // text manager's positions: unwrap to the text manager's leaf position
                Position pos = box.getPosition();
                Position leaf = pos;
                while (leaf != null && !(leaf instanceof LeafPosition)) {
                    leaf = leaf.getPosition();
                }
                if (leaf == null || !(leaf.getLM() instanceof org.apache.fop.layoutmgr.inline.TextLayoutManager)) continue;
                org.apache.fop.layoutmgr.inline.TextLayoutManager tlm = (org.apache.fop.layoutmgr.inline.TextLayoutManager) leaf.getLM();
                MinOptMax ls = LBP.letterSpaceIPD(tlm);
                if (ls == null || (ls.getOpt() == 0 && ls.getStretch() == 0 && ls.getShrink() == 0)) continue;
                List<org.apache.fop.fonts.GlyphMapping> mappings = LBP.mappings(tlm);
                int idx = ((LeafPosition) leaf).getLeafPos();
                if (idx < 0 || idx >= mappings.size()) continue;
                org.apache.fop.fonts.GlyphMapping m = mappings.get(idx);
                if (m.isSpace || m.letterSpaceCount != 0 || m.font == null
                        || !(m.font.performsSubstitution() || m.font.performsPositioning())) continue;
                int wordLength = m.getWordLength();
                if (wordLength <= 0) continue;
                org.apache.fop.fo.FOText foText = LBP.foText(tlm);
                // processWordNoMapping's rule: the break character after the word counts
                // as a letter space unless it is a space.  Measured against Word
                // (spacing-char, 0.25/1/3pt expanded, 0.5pt condensed): every line
                // breaks as Word's bar one 0.3pt-marginal case; counting a letter space
                // after every character instead (Word's rendering) broke lines a word
                // early throughout.
                boolean breakOpp = m.breakOppAfter && m.endIndex < foText.length()
                        && !Character.isWhitespace(foText.charAt(m.endIndex));
                int spaces = wordLength - 1 + (breakOpp ? 1 : 0);
                m.breakOppAfter = breakOpp;
                m.letterSpaceCount = spaces;
                m.areaIPD = m.areaIPD.plus(ls.mult(spaces));
                boolean suppressible = breakOpp && !m.isHyphenated;
                int width = ls.isStiff()
                        ? (suppressible ? m.areaIPD.getOpt() - ls.getOpt() : m.areaIPD.getOpt())
                        : m.areaIPD.getOpt() - spaces * ls.getOpt();
                if (WordLineLayoutManager.log.isDebugEnabled()) {
                    WordLineLayoutManager.log.debug("letter spaces restored: word " + m.startIndex + "-" + m.endIndex
                            + " +" + spaces + " x " + ls.getOpt() + " -> box " + width);
                }
                seq.set(i, new KnuthInlineBox(width, box.getAlignmentContext(), pos, box.isAuxiliary()));
            }
        }
    }

    private void collectInlineKnuthElements(LayoutContext context) {
        LayoutContext inlineLC = LayoutContext.copyOf(context);

        // convert all the text in a sequence of paragraphs made
        // of KnuthBox, KnuthGlue and KnuthPenalty objects
        boolean previousIsBox = false;

        StringBuffer trace = new StringBuffer("LineLM:");

        Paragraph lastPar = null;

        InlineLevelLayoutManager curLM;
        while ((curLM = (InlineLevelLayoutManager) getChildLM()) != null) {
            List<KnuthSequence> inlineElements = curLM.getNextKnuthElements(inlineLC, effectiveAlignment);
            fixLetterSpaces(curLM, inlineElements);
            if (inlineElements == null || inlineElements.size() == 0) {
                /* curLM.getNextKnuthElements() returned null or an empty list;
                 * this can happen if there is nothing more to layout,
                 * so just iterate once more to see if there are other children */
                continue;
            }

            if (lastPar != null) {
                KnuthSequence firstSeq = inlineElements.get(0);

                // finish last paragraph before a new block sequence
                if (!firstSeq.isInlineSequence()) {
                    lastPar.endParagraph();
                    ElementListObserver.observe(lastPar, "line", null);
                    lastPar = null;
                    if (WordLineLayoutManager.log.isTraceEnabled()) {
                        trace.append(" ]");
                    }
                    previousIsBox = false;
                }

                // does the first element of the first paragraph add to an existing word?
                if (lastPar != null) {
                    KnuthElement thisElement;
                    thisElement = (KnuthElement) firstSeq.get(0);
                    if (thisElement.isBox() && !thisElement.isAuxiliary()
                            && previousIsBox) {
                        lastPar.addALetterSpace();
                    }
                }
            }

            // loop over the KnuthSequences (and single KnuthElements) in returnedList
            for (Object inlineElement : inlineElements) {
                KnuthSequence sequence = (KnuthSequence) inlineElement;
                // the sequence contains inline Knuth elements
                if (sequence.isInlineSequence()) {
                    // look at the last element
                    ListElement lastElement = sequence.getLast();
                    assert lastElement != null;
                    previousIsBox = lastElement.isBox()
                            && !((KnuthElement) lastElement).isAuxiliary()
                            && ((KnuthElement) lastElement).getWidth() != 0;

                    // if last paragraph is open, add the new elements to the paragraph
                    // else this is the last paragraph
                    if (lastPar == null) {
                        lastPar = new Paragraph(this,
                                textAlignment, textAlignmentLast,
                                textIndent.getValue(this),
                                lastLineEndIndent.getValue(this));
                        lastPar.startSequence();
                        if (WordLineLayoutManager.log.isTraceEnabled()) {
                            trace.append(" [");
                        }
                    } else {
                        if (WordLineLayoutManager.log.isTraceEnabled()) {
                            trace.append(" +");
                        }
                    }
                    lastPar.addAll(sequence);
                    if (WordLineLayoutManager.log.isTraceEnabled()) {
                        trace.append(" I");
                    }

                    // finish last paragraph if it was closed with a linefeed
                    if (lastElement.isPenalty()
                            && ((KnuthPenalty) lastElement).getPenalty()
                            == -KnuthPenalty.INFINITE) {
                        // a penalty item whose value is -inf
                        // represents a preserved linefeed,
                        // which forces a line break
                        lastPar.removeLast();
                        if (!lastPar.containsBox()) {
                            //only a forced linefeed on this line
                            //-> compensate with an auxiliary glue
                            lastPar.add(new KnuthGlue(ipd, 0, ipd, null, true));
                        }
                        lastPar.endParagraph();
                        ElementListObserver.observe(lastPar, "line", null);
                        lastPar = null;
                        if (WordLineLayoutManager.log.isTraceEnabled()) {
                            trace.append(" ]");
                        }
                        previousIsBox = false;
                    }
                } else { // the sequence is a block sequence
                    // the positions will be wrapped with this LM in postProcessLineBreaks
                    knuthParagraphs.add(sequence);
                    if (WordLineLayoutManager.log.isTraceEnabled()) {
                        trace.append(" B");
                    }
                }
            } // end of loop over returnedList
        }

        if (lastPar != null) {
            lastPar.endParagraph();
            ElementListObserver.observe(lastPar, "line", fobj.getId());
            if (WordLineLayoutManager.log.isTraceEnabled()) {
                trace.append(" ]");
            }
        }
        WordLineLayoutManager.log.trace("{}", trace);
    }

    /**
     * Phase 2 of Knuth algorithm: find optimal break points.
     * @param alignment alignment in BP direction of the paragraph
     * @param context the layout context
     * @return a list of Knuth elements representing broken lines
     */
    private List<ListElement> createLineBreaks(int alignment, LayoutContext context) {
        // find the optimal line breaking points for each paragraph
        Iterator<KnuthSequence> paragraphsIterator = knuthParagraphs.iterator();
        lineLayoutsList = new LineLayoutPossibilities[knuthParagraphs.size()];
        LineLayoutPossibilities llPoss;
        for (int i = 0; paragraphsIterator.hasNext(); i++) {
            KnuthSequence seq = paragraphsIterator.next();
            if (!seq.isInlineSequence()) {
                // This set of line layout possibilities does not matter;
                // we only need an entry in lineLayoutsList.
                llPoss = new LineLayoutPossibilities();
            } else {
                llPoss = findOptimalBreakingPoints(alignment, (Paragraph) seq,
                                                   !paragraphsIterator.hasNext());
            }
            lineLayoutsList[i] = llPoss;
        }

        setFinished(true);

        //Post-process the line breaks found
        return postProcessLineBreaks(alignment, context);
    }

    /**
     * Find the optimal linebreaks for a paragraph
     * @param alignment alignment of the paragraph
     * @param currPar the Paragraph for which the linebreaks are found
     * @param isLastPar flag indicating whether currPar is the last paragraph
     * @return the line layout possibilities for the paragraph
     */
    /**
     * Word breaks lines greedily (first fit): a line takes every word that fits and
     * breaks at the last opportunity before the first word that does not, with
     * no look-ahead.  FOP's total-fit (Knuth-Plass) search chooses breaks that
     * minimise badness over the whole paragraph, so even ragged-right text
     * breaks differently in about a quarter of lines with identical fonts and
     * widths (CR-001 harness, break-ragged).  This runs the greedy algorithm
     * once; there is no threshold ladder because it always succeeds.
     * Hyphenation points are used when the block asks for them.
     */
    private LineLayoutPossibilities findOptimalBreakingPoints(int alignment, Paragraph currPar,
                                                              boolean isLastPar) {
        lineLayouts = new LineLayoutPossibilities();
        LineBreakingAlgorithm alg = new LineBreakingAlgorithm(alignment,
                                        textAlignment, textAlignmentLast,
                                        textIndent.getValue(this), currPar.lineFiller.getOpt(),
                                        lineHeight.getValue(this), lead, follow,
                                        (knuthParagraphs.indexOf(currPar) == 0),
                                        hyphenationLadderCount.getEnum() == EN_NO_LIMIT
                                            ? 0 : hyphenationLadderCount.getValue(),
                                        this);
        alg.setConstantLineWidth(ipd);
        boolean canWrap = (wrapOption != EN_NO_WRAP);
        boolean canHyphenate = (canWrap && hyphenationProperties.hyphenate.getEnum() == EN_TRUE);
        if (canHyphenate && !hyphenationPerformed) {
            hyphenationPerformed = isLastPar;
            findHyphenationPoints(currPar);
        }
        int allowedBreaks = !canWrap ? BreakingAlgorithm.ONLY_FORCED_BREAKS
                : (canHyphenate ? BreakingAlgorithm.ALL_BREAKS : BreakingAlgorithm.NO_FLAGGED_PENALTIES);
        alg.findBreakingPoints(currPar, 1, true, allowedBreaks);
        return lineLayouts;
    }

    private List<ListElement> postProcessLineBreaks(int alignment, LayoutContext context) {

        List<ListElement> returnList = new LinkedList<>();

        int endIndex = -1;
        // Word lines: the previous line's extra leading, to be emitted after the
        // break possibility that follows the line (glue after a taken break is
        // dropped, so the last line of a page keeps only its text box)
        int pendingLeading = 0;
        for (int p = 0; p < knuthParagraphs.size(); p++) {
            // penalty between paragraphs
            if (p > 0) {
                Keep keep = getKeepTogether();
                returnList.add(new BreakElement(
                            new Position(this),
                            keep.getPenalty(),
                            keep.getContext(),
                            context));
                if (pendingLeading > 0) {
                    returnList.add(new LeadingGlue(pendingLeading));
                    pendingLeading = 0;
                }
            }

            LineLayoutPossibilities llPoss = lineLayoutsList[p];
            KnuthSequence seq = knuthParagraphs.get(p);

            if (!seq.isInlineSequence()) {
                List<ListElement> targetList = new LinkedList<ListElement>();
                for (Object aSeq : seq) {
                    ListElement tempElement;
                    tempElement = (ListElement) aSeq;
                    LayoutManager lm = tempElement.getLayoutManager();
                    if (baselineOffset < 0 && lm != null && lm.hasLineAreaDescendant()) {
                        baselineOffset = lm.getBaselineOffset();
                    }
                    if (lm != this) {
                        tempElement.setPosition(notifyPos(new NonLeafPosition(this,
                                tempElement.getPosition())));
                    }
                    targetList.add(tempElement);
                }
                returnList.addAll(targetList);
            } else if (seq.isInlineSequence() && alignment == EN_JUSTIFY) {
                /* justified vertical alignment (not in the XSL FO recommendation):
                   create a multi-layout sequence whose elements will contain
                   a conventional Position */
                Position returnPosition = new LeafPosition(this, p);
                createElements(returnList, llPoss, returnPosition);
            } else {
                /* "normal" vertical alignment: create a sequence whose boxes
                   represent effective lines, and contain LineBreakPositions */
                int startIndex = 0;
                int previousEndIndex = 0;
                for (int i = 0;
                        i < llPoss.getChosenLineCount();
                        i++) {
                    int orphans = fobj.getOrphans();
                    int widows = fobj.getWidows();
                    if (handlingFloat()) {
                        orphans = 1;
                        widows = 1;
                    }
                    if (returnList.size() > 0
                            && i > 0 //if i==0 break generated above already
                            && i >= orphans && i <= llPoss.getChosenLineCount() - widows) {
                        // penalty allowing a page break between lines
                        Keep keep = getKeepTogether();
                        returnList.add(new BreakElement(
                                new LeafPosition(this, p, endIndex),
                                    keep.getPenalty(),
                                    keep.getContext(),
                                    context));
                    } else if (i > 0 && pendingLeading > 0) {
                        // no break allowed here: the glue must not become one
                        returnList.add(new KnuthPenalty(0, KnuthElement.INFINITE, false, null, true));
                    }
                    if (i > 0 && pendingLeading > 0) {
                        returnList.add(new LeadingGlue(pendingLeading));
                        pendingLeading = 0;
                    }
                    endIndex = llPoss.getChosenPosition(i).getLeafPos();
                    // create a list of the FootnoteBodyLM handling footnotes
                    // whose citations are in this line
                    List<FootnoteBodyLayoutManager> footnoteList = FootenoteUtil.getFootnotes(
                            seq, startIndex, endIndex);
                    List<FloatContentLayoutManager> floats = FloatContentLayoutManager.checkForFloats(seq,
                            startIndex, endIndex);
                    startIndex = endIndex + 1;
                    LineBreakPosition lbp = llPoss.getChosenPosition(i);
                    if (baselineOffset < 0) {
                        baselineOffset = LBP.spaceBefore(lbp) + LBP.baseline(lbp);
                    }
                    // a Word line's leading (spaceAfter) goes into LeadingGlue after the
                    // next break possibility; FOP's lines keep it in the box
                    int boxHeight = LBP.lineHeight(lbp) + LBP.spaceBefore(lbp)
                            + (wordLineBox > 0 ? 0 : LBP.spaceAfter(lbp));
                    if (floats.isEmpty()) {
                        returnList.add(new KnuthBlockBox(boxHeight, footnoteList, lbp, false));
                    } else {
                        // add a line with height zero and no content and attach float to it
                        returnList.add(new KnuthBlockBox(0, Collections.emptyList(), null, false, floats));
                        // add a break element to signal that we should restart LB at this break
                        Keep keep = getKeepTogether();
                        returnList.add(new BreakElement(new LeafPosition(this, p, previousEndIndex), keep
                                .getPenalty(), keep.getContext(), context));
                        // add the original line where the float was but without the float now
                        returnList.add(new KnuthBlockBox(boxHeight, footnoteList, lbp, false));
                    }
                    if (wordLineBox > 0) {
                        pendingLeading = LBP.spaceAfter(lbp);
                    }
                    previousEndIndex = endIndex;
                }
            }
        }
        if (pendingLeading > 0) {
            // the last line's leading; WordFlowLayoutManager moves it behind the
            // break possibility the flow adds after this block.  The empty box keeps
            // the list from ending in glue, which the flow would take for a break
            // possibility of its own and add no penalty (BlockStackingLayoutManager
            // .addInBetweenBreak: "glue-type break possibility not handled properly").
            returnList.add(new KnuthPenalty(0, KnuthElement.INFINITE, false, null, true));
            returnList.add(new LeadingGlue(pendingLeading));
            returnList.add(new KnuthBox(0, null, true));
        }

        return returnList;
    }

    private void createElements(List<ListElement> list, LineLayoutPossibilities llPoss,
                                Position elementPosition) {
        /* number of normal, inner lines */
        int innerLines = 0;
        /* number of lines that can be used in order to fill more space */
        int optionalLines = 0;
        /* number of lines that can be used in order to fill more space
           only if the paragraph is not parted */
        int conditionalOptionalLines = 0;
        /* number of lines that can be omitted in order to fill less space */
        int eliminableLines = 0;
        /* number of lines that can be omitted in order to fill less space
           only if the paragraph is not parted */
        int conditionalEliminableLines = 0;
        /* number of the first unbreakable lines */
        int firstLines = fobj.getOrphans();
        /* number of the last unbreakable lines */
        int lastLines = fobj.getWidows();
        /* sub-sequence used to separate the elements representing different lines */
        List<KnuthElement> breaker = new LinkedList<KnuthElement>();

        /* comment out the next lines in order to test particular situations */
        if (fobj.getOrphans() + fobj.getWidows() <= llPoss.getMinLineCount()) {
            innerLines = llPoss.getMinLineCount() - (fobj.getOrphans() + fobj.getWidows());
            optionalLines = llPoss.getMaxLineCount() - llPoss.getOptLineCount();
            eliminableLines = llPoss.getOptLineCount() - llPoss.getMinLineCount();
        } else if (fobj.getOrphans() + fobj.getWidows() <= llPoss.getOptLineCount()) {
            optionalLines = llPoss.getMaxLineCount() - llPoss.getOptLineCount();
            eliminableLines = llPoss.getOptLineCount() - (fobj.getOrphans() + fobj.getWidows());
            conditionalEliminableLines
                    = (fobj.getOrphans() + fobj.getWidows()) - llPoss.getMinLineCount();
        } else if (fobj.getOrphans() + fobj.getWidows() <= llPoss.getMaxLineCount()) {
            optionalLines = llPoss.getMaxLineCount() - (fobj.getOrphans() + fobj.getWidows());
            conditionalOptionalLines
                    = (fobj.getOrphans() + fobj.getWidows()) - llPoss.getOptLineCount();
            conditionalEliminableLines = llPoss.getOptLineCount() - llPoss.getMinLineCount();
            firstLines -= conditionalOptionalLines;
        } else {
            conditionalOptionalLines = llPoss.getMaxLineCount() - llPoss.getOptLineCount();
            conditionalEliminableLines = llPoss.getOptLineCount() - llPoss.getMinLineCount();
            firstLines = llPoss.getOptLineCount();
            lastLines = 0;
        }
        /* comment out the previous lines in order to test particular situations */

        /* use these lines to test particular situations
        innerLines = 0;
        optionalLines = 1;
        conditionalOptionalLines = 2;
        eliminableLines = 0;
        conditionalEliminableLines = 0;
        firstLines = 1;
        lastLines = 3;
        */

        if (lastLines != 0
            && (conditionalOptionalLines > 0 || conditionalEliminableLines > 0)) {
            breaker.add(new KnuthPenalty(0, KnuthElement.INFINITE, false, elementPosition, false));
            breaker.add(new KnuthGlue(0, -conditionalOptionalLines * constantLineHeight,
                                        -conditionalEliminableLines * constantLineHeight,
                                        Adjustment.LINE_NUMBER_ADJUSTMENT, elementPosition, false));
            breaker.add(new KnuthPenalty(conditionalOptionalLines * constantLineHeight,
                                           0, false, elementPosition, false));
            breaker.add(new KnuthGlue(0, conditionalOptionalLines * constantLineHeight,
                                        conditionalEliminableLines * constantLineHeight,
                                        Adjustment.LINE_NUMBER_ADJUSTMENT, elementPosition, false));
        } else if (lastLines != 0) {
            breaker.add(new KnuthPenalty(0, 0, false, elementPosition, false));
        }

        // creation of the elements:
        // first group of lines
        list.add(new KnuthBox(firstLines * constantLineHeight, elementPosition,
                              (lastLines == 0
                               && conditionalOptionalLines == 0
                               && conditionalEliminableLines == 0)));
        if (conditionalOptionalLines > 0
            || conditionalEliminableLines > 0) {
            list.add(new KnuthPenalty(0, KnuthElement.INFINITE, false, elementPosition, false));
            list.add(new KnuthGlue(0, conditionalOptionalLines * constantLineHeight,
                                   conditionalEliminableLines * constantLineHeight,
                                   Adjustment.LINE_NUMBER_ADJUSTMENT, elementPosition, false));
            list.add(new KnuthBox(0, elementPosition, (lastLines == 0)));
        }

        // optional lines
        for (int i = 0; i < optionalLines; i++) {
            list.addAll(breaker);
            list.add(new KnuthBox(0, elementPosition, false));
            list.add(new KnuthPenalty(0, KnuthElement.INFINITE, false, elementPosition, false));
            list.add(new KnuthGlue(0, constantLineHeight, 0,
                                   Adjustment.LINE_NUMBER_ADJUSTMENT, elementPosition, false));
            list.add(new KnuthBox(0, elementPosition, false));
        }

        // eliminable lines
        for (int i = 0; i < eliminableLines; i++) {
            list.addAll(breaker);
            list.add(new KnuthBox(constantLineHeight, elementPosition, false));
            list.add(new KnuthPenalty(0, KnuthElement.INFINITE, false, elementPosition, false));
            list.add(new KnuthGlue(0, 0, constantLineHeight,
                                   Adjustment.LINE_NUMBER_ADJUSTMENT, elementPosition, false));
            list.add(new KnuthBox(0, elementPosition, false));
        }

        // inner lines
        for (int i = 0; i < innerLines; i++) {
            list.addAll(breaker);
            list.add(new KnuthBox(constantLineHeight, elementPosition, false));
        }

        // last group of lines
        if (lastLines > 0) {
            list.addAll(breaker);
            list.add(new KnuthBox(lastLines * constantLineHeight,
                                  elementPosition, true));
        }
    }

    /** {@inheritDoc} */
    public boolean mustKeepTogether() {
        return ((BlockLevelLayoutManager) getParent()).mustKeepTogether();
    }

    /** {@inheritDoc} */
    public KeepProperty getKeepTogetherProperty() {
        return ((BlockLevelLayoutManager) getParent()).getKeepTogetherProperty();
    }

    /** {@inheritDoc} */
    public KeepProperty getKeepWithPreviousProperty() {
        return ((BlockLevelLayoutManager) getParent()).getKeepWithPreviousProperty();
    }

    /** {@inheritDoc} */
    public KeepProperty getKeepWithNextProperty() {
        return ((BlockLevelLayoutManager) getParent()).getKeepWithNextProperty();
    }

    /** {@inheritDoc} */
    public Keep getKeepTogether() {
        return ((BlockLevelLayoutManager) getParent()).getKeepTogether();
    }

    /** {@inheritDoc} */
    public boolean mustKeepWithPrevious() {
        return !getKeepWithPrevious().isAuto();
    }

    /** {@inheritDoc} */
    public boolean mustKeepWithNext() {
        return !getKeepWithNext().isAuto();
    }

    /** {@inheritDoc} */
    public Keep getKeepWithNext() {
        return Keep.KEEP_AUTO;
    }

    /** {@inheritDoc} */
    public Keep getKeepWithPrevious() {
        return Keep.KEEP_AUTO;
    }

    /** {@inheritDoc} */
    public int negotiateBPDAdjustment(int adj, KnuthElement lastElement) {
        Position lastPos = lastElement.getPosition();
        assert (lastPos instanceof LeafPosition);
        LeafPosition pos = (LeafPosition) lastPos;
        //if (lastElement.isPenalty()) {
        //    totalAdj += lastElement.getWidth();
        //}
        //int lineNumberDifference = (int)((double) totalAdj / constantLineHeight);
        int lineNumberDifference = (int) Math.round((double) adj / constantLineHeight
                                                    + (adj > 0 ? -0.4 : 0.4));
        //log.debug("   LLM> variazione calcolata = " + ((double) totalAdj / constantLineHeight)
        //+ " variazione applicata = " + lineNumberDifference);
        LineLayoutPossibilities llPoss;
        llPoss = lineLayoutsList[pos.getLeafPos()];
        lineNumberDifference = llPoss.applyLineCountAdjustment(lineNumberDifference);
        return lineNumberDifference * constantLineHeight;
    }

    /** {@inheritDoc} */
    public void discardSpace(KnuthGlue spaceGlue) {
    }

    /** {@inheritDoc} */
    @Override
    public List<ListElement> getChangedKnuthElements(List<ListElement> oldList, int alignment, int depth) {
        return getChangedKnuthElements(oldList, alignment);
    }

    /** {@inheritDoc} */
    @Override
    public List<ListElement> getChangedKnuthElements(List<ListElement> oldList, int alignment) {
        List<ListElement> returnList = new LinkedList<>();
        for (int p = 0; p < knuthParagraphs.size(); p++) {
            LineLayoutPossibilities llPoss = lineLayoutsList[p];
            //log.debug("demerits of the chosen layout: " + llPoss.getChosenDemerits());
            int orphans = fobj.getOrphans();
            int widows = fobj.getWidows();
            if (handlingFloat()) {
                orphans = 1;
                widows = 1;
            }
            for (int i = 0; i < llPoss.getChosenLineCount(); i++) {
                if (!((BlockLevelLayoutManager) parentLayoutManager).mustKeepTogether() && i >= orphans
                        && i <= llPoss.getChosenLineCount() - widows) {
                    // null penalty allowing a page break between lines
                    returnList.add(new KnuthPenalty(0, 0, false, new Position(this), false));
                }
                LineBreakPosition lbp = llPoss.getChosenPosition(i);
                //log.debug("LLM.getChangedKnuthElements> lineWidth= "
                // + LBP.lineWidth(lbp) + " difference= " + LBP.difference(lbp));
                //log.debug("                             shrink= "
                // + LBP.availableShrink(lbp) + " stretch= " + LBP.availableStretch(lbp));
                //log.debug("linewidth= " + LBP.lineWidth(lbp) + " difference= "
                //+ LBP.difference(lbp) + " indent= " + LBP.startIndent(lbp));
                MinOptMax contentIPD;
                if (alignment == EN_JUSTIFY) {
                    contentIPD = MinOptMax.getInstance(
                        LBP.lineWidth(lbp) - LBP.difference(lbp) - LBP.availableShrink(lbp),
                        LBP.lineWidth(lbp) - LBP.difference(lbp),
                        LBP.lineWidth(lbp) - LBP.difference(lbp) + LBP.availableStretch(lbp));
                } else if (alignment == EN_CENTER) {
                    contentIPD = MinOptMax.getInstance(LBP.lineWidth(lbp) - 2 * LBP.startIndent(lbp));
                } else if (alignment == EN_END) {
                    contentIPD = MinOptMax.getInstance(LBP.lineWidth(lbp) - LBP.startIndent(lbp));
                } else {
                    contentIPD
                        = MinOptMax.getInstance(LBP.lineWidth(lbp) - LBP.difference(lbp) + LBP.startIndent(lbp));
                }
                returnList.add(new KnuthBlockBox(LBP.lineHeight(lbp), contentIPD, (LBP.ipdAdjust(lbp) != 0
                        ? LBP.lineWidth(lbp) - LBP.difference(lbp) : 0),
                                                 lbp, false));
            }
        }
        return returnList;
    }

    /**
     * Find hyphenation points for every word in the current paragraph.
     *
     * @param currPar the paragraph whose words will be hyphenated
     */
    private void findHyphenationPoints(Paragraph currPar) {
        // hyphenate every word
        ListIterator currParIterator = currPar.listIterator(currPar.ignoreAtStart);
        // list of TLM involved in hyphenation
        List<Update> updateList = new LinkedList<>();
        KnuthElement firstElement;
        KnuthElement nextElement;
        // current InlineLevelLayoutManager
        InlineLevelLayoutManager currLM = null;
        // number of KnuthBox elements containing word fragments
        int boxCount;
        // number of auxiliary KnuthElements between KnuthBoxes
        int auxCount;
        StringBuffer sbChars;

        // find all hyphenation points
        while (currParIterator.hasNext()) {
            firstElement = (KnuthElement) currParIterator.next();
            //
            if (firstElement.getLayoutManager() != currLM) {
                currLM = (InlineLevelLayoutManager) firstElement.getLayoutManager();
                if (currLM != null) {
                    updateList.add(new Update(currLM, currParIterator.previousIndex()));
                } else {
                    break;
                }
            } else if (currLM == null) {
                break;
            }

            // collect word fragments, ignoring auxiliary elements;
            // each word fragment was created by a different TextLM
            if (firstElement.isBox() && !firstElement.isAuxiliary()) {
                boxCount = 1;
                auxCount = 0;
                sbChars = new StringBuffer();
                sbChars.append(currLM.getWordChars(firstElement.getPosition()));
                // look if next elements are boxes too
                while (currParIterator.hasNext()) {
                    nextElement = (KnuthElement) currParIterator.next();
                    if (nextElement.isBox() && !nextElement.isAuxiliary()) {
                        // a non-auxiliary KnuthBox: append word chars
                        if (currLM != nextElement.getLayoutManager()) {
                            currLM = (InlineLevelLayoutManager) nextElement.getLayoutManager();
                            updateList.add(new Update(currLM, currParIterator.previousIndex()));
                        }
                        // append text to recreate the whole word
                        boxCount++;
                        sbChars.append(currLM.getWordChars(nextElement.getPosition()));
                    } else if (!nextElement.isAuxiliary()) {
                        // a non-auxiliary non-box KnuthElement: stop
                        // go back to the last box or auxiliary element
                        currParIterator.previous();
                        break;
                    } else {
                        if (currLM != nextElement.getLayoutManager()) {
                            currLM = (InlineLevelLayoutManager) nextElement.getLayoutManager();
                            updateList.add(new Update(currLM, currParIterator.previousIndex()));
                        }
                        // an auxiliary KnuthElement: simply ignore it
                        auxCount++;
                    }
                }
                if (log.isTraceEnabled()) {
                    log.trace(" Word to hyphenate: " + sbChars);
                }
                // find hyphenation points
                HyphContext hc = getHyphenContext(sbChars);
                // ask each LM to hyphenate its word fragment
                if (hc != null) {
                    KnuthElement element = null;
                    for (int i = 0; i < (boxCount + auxCount); i++) {
                        currParIterator.previous();
                    }
                    for (int i = 0; i < (boxCount + auxCount); i++) {
                        element = (KnuthElement) currParIterator.next();
                        if (element.isBox() && !element.isAuxiliary()) {
                            ((InlineLevelLayoutManager)
                             element.getLayoutManager()).hyphenate(element.getPosition(), hc);
                        } else {
                            // nothing to do, element is an auxiliary KnuthElement
                        }
                    }
                }
            }
        }
        processUpdates(currPar, updateList);
    }

    private void processUpdates(Paragraph par, List<Update> updateList) {
        // create iterator for the updateList
        ListIterator updateListIterator = updateList.listIterator();
        Update currUpdate;
        int elementsAdded = 0;

        while (updateListIterator.hasNext()) {
            // ask the LMs to apply the changes and return
            // the new KnuthElements to replace the old ones
            currUpdate = (Update) updateListIterator.next();
            int fromIndex = currUpdate.firstIndex;
            int toIndex;
            if (updateListIterator.hasNext()) {
                Update nextUpdate = (Update) updateListIterator.next();
                toIndex = nextUpdate.firstIndex;
                updateListIterator.previous();
            } else {
                // maybe this is not always correct!
                toIndex = par.size() - par.ignoreAtEnd
                    - elementsAdded;
            }

            // applyChanges() returns true if the LM modifies its data,
            // so it must return new KnuthElements to replace the old ones
            if (currUpdate.inlineLM
                .applyChanges(par.subList(fromIndex + elementsAdded,
                                              toIndex + elementsAdded))) {
                // insert the new KnuthElements
                List<ListElement> newElements = currUpdate.inlineLM.getChangedKnuthElements(
                    par.subList(fromIndex + elementsAdded,
                                     toIndex + elementsAdded),
                     /*flaggedPenalty,*/ effectiveAlignment);
                // remove the old elements
                par.subList(fromIndex + elementsAdded,
                                toIndex + elementsAdded).clear();
                // insert the new elements
                par.addAll(fromIndex + elementsAdded, newElements);
                elementsAdded += newElements.size() - (toIndex - fromIndex);
            }
        }
        updateList.clear();
    }

    /**
     * Line area is always considered to act as a fence.
     * @param isNotFirst ignored
     * @return always true
     */
    @Override
    protected boolean hasLeadingFence(boolean isNotFirst) {
        return true;
    }

    /**
     * Line area is always considered to act as a fence.
     * @param isNotLast ignored
     * @return always true
     */
    @Override
    protected boolean hasTrailingFence(boolean isNotLast) {
        return true;
    }

    private HyphContext getHyphenContext(StringBuffer sbChars) {
        // Find all hyphenation points in this word
        // (get in an array of offsets)
        // hyphenationProperties are from the block level?.
        // Note that according to the spec,
        // they also "apply to" fo:character.
        // I don't know what that means, since
        // if we change language in the middle of a "word",
        // the effect would seem quite strange!
        // Or perhaps in that case, we say that it's several words.
        // We probably should bring the hyphenation props up from the actual
        // TextLM which generate the hyphenation buffer,
        // since these properties inherit and could be specified
        // on an inline or wrapper below the block level.
        Hyphenation hyph = Hyphenator.hyphenate(hyphenationProperties.language.getString(),
                               hyphenationProperties.country.getString(),
                               getFObj().getUserAgent().getHyphenationResourceResolver(),
                               getFObj().getUserAgent().getHyphenationPatternNames(),
                               sbChars.toString(),
                               hyphenationProperties.hyphenationRemainCharacterCount.getValue(),
                               hyphenationProperties.hyphenationPushCharacterCount.getValue(),
                               getFObj().getUserAgent());
        // They hyph structure contains the information we need
        // Now start from prev: reset to that position, ask that LM to get
        // a Position for the first hyphenation offset. If the offset isn't in
        // its characters, it returns null,
        // but must tell how many chars it had.
        // Keep looking at currentBP using next hyphenation point until the
        // returned size is greater than the available size
        // or no more hyphenation points remain. Choose the best break.
        if (hyph != null) {
            return new HyphContext(hyph.getHyphenationPoints());
        } else {
            return null;
        }
    }

    @Override
    public boolean hasLineAreaDescendant() {
        return true;
    }

    @Override
    public int getBaselineOffset() {
        return baselineOffset;
    }

    /**
     * Add the areas with the break points.
     *
     * @param parentIter the iterator of break positions
     * @param context the context for adding areas
     */
    @Override
    public void addAreas(PositionIterator parentIter,
                         LayoutContext context) {
        while (parentIter.hasNext()) {
            Position pos = parentIter.next();
            boolean isLastPosition = !parentIter.hasNext();
            if (pos instanceof LineBreakPosition) {
                addInlineArea(context, (LineBreakPosition) pos, isLastPosition);
            } else if ((pos instanceof NonLeafPosition) && pos.generatesAreas()) {
                addBlockArea(context, pos, isLastPosition);
            } else {
                /*
                 * pos was the Position inside a penalty item, nothing to do;
                 * or Pos does not generate an area,
                 * i.e. it stand for spaces, borders and padding.
                 */
            }
        }
        setCurrentArea(null); // ?? necessary
    }

    /**
     * Add a line with inline content
     * @param context the context for adding areas
     * @param lbp the position for which the line is generated
     * @param isLastPosition true if this is the last position of this LM
     */
    private void addInlineArea(LayoutContext context, LineBreakPosition lbp,
            boolean isLastPosition) {

        KnuthSequence seq = knuthParagraphs.get(LBP.parIndex(lbp));
        int startElementIndex = LBP.startIndex(lbp);
        int endElementIndex = lbp.getLeafPos();

        LineArea lineArea = new LineArea(
                (lbp.getLeafPos() < seq.size() - 1 ? textAlignment : textAlignmentLast),
                LBP.difference(lbp), LBP.availableStretch(lbp), LBP.availableShrink(lbp));
        lineArea.setChangeBarList(getChangeBarList());

        if (LBP.startIndent(lbp) != 0) {
            lineArea.addTrait(Trait.START_INDENT, LBP.startIndent(lbp));
        }
        if (LBP.endIndent(lbp) != 0) {
            lineArea.addTrait(Trait.END_INDENT, LBP.endIndent(lbp));
        }
        lineArea.setBPD(LBP.lineHeight(lbp));
        lineArea.setIPD(LBP.lineWidth(lbp));
        lineArea.setBidiLevel(bidiLevel);
        lineArea.addTrait(Trait.SPACE_BEFORE, LBP.spaceBefore(lbp));
        lineArea.addTrait(Trait.SPACE_AFTER, LBP.spaceAfter(lbp));
        alignmentContext.resizeLine(LBP.lineHeight(lbp), LBP.baseline(lbp));

        if (seq instanceof Paragraph) {
            Paragraph currPar = (Paragraph) seq;
            // ignore the first elements added by the LineLayoutManager
            startElementIndex += (startElementIndex == 0) ? currPar.ignoreAtStart : 0;

            // if this is the last line area that for this paragraph,
            // ignore the last elements added by the LineLayoutManager and
            // subtract the last-line-end-indent from the area ipd
            if (endElementIndex == (currPar.size() - 1)) {
                endElementIndex -= currPar.ignoreAtEnd;
                lineArea.setIPD(lineArea.getIPD() - lastLineEndIndent.getValue(this));
            }
        }

        // ignore the last element in the line if it is a KnuthGlue object
        ListIterator seqIterator = seq.listIterator(endElementIndex);
        KnuthElement lastElement = (KnuthElement) seqIterator.next();
        // the TLM which created the last KnuthElement in this line
        LayoutManager lastLM = lastElement.getLayoutManager();
        if (lastElement.isGlue()) {
            // Remove trailing spaces if allowed so
            if (whiteSpaceTreament == EN_IGNORE_IF_SURROUNDING_LINEFEED
                    || whiteSpaceTreament == EN_IGNORE
                    || whiteSpaceTreament == EN_IGNORE_IF_BEFORE_LINEFEED) {
                endElementIndex--;
                // this returns the same KnuthElement
                seqIterator.previous();
                if (seqIterator.hasPrevious()) {
                    lastLM = ((KnuthElement) seqIterator.previous()).getLayoutManager();
                }
            }
        }

        // Remove leading spaces if allowed so
        if (whiteSpaceTreament == EN_IGNORE_IF_SURROUNDING_LINEFEED
                || whiteSpaceTreament == EN_IGNORE
                || whiteSpaceTreament == EN_IGNORE_IF_AFTER_LINEFEED) {
            // ignore KnuthGlue and KnuthPenalty objects
            // at the beginning of the line
            seqIterator = seq.listIterator(startElementIndex);
            while (seqIterator.hasNext() && !((KnuthElement) seqIterator.next()).isBox()) {
                startElementIndex++;
            }
        }
        // Add the inline areas to lineArea
        PositionIterator inlinePosIter = new KnuthPossPosIter(seq, startElementIndex,
                endElementIndex + 1);

        LayoutContext lc = LayoutContext.offspringOf(context);
        lc.setAlignmentContext(alignmentContext);
        lc.setSpaceAdjust(LBP.dAdjust(lbp));
        lc.setIPDAdjust(LBP.ipdAdjust(lbp));
        lc.setLeadingSpace(new SpaceSpecifier(true));
        lc.setTrailingSpace(new SpaceSpecifier(false));
        lc.setFlags(LayoutContext.RESOLVE_LEADING_SPACE, true);

        setCurrentArea(lineArea);
        setChildContext(lc);
        LayoutManager childLM;
        while ((childLM = inlinePosIter.getNextChildLM()) != null) {
            lc.setFlags(LayoutContext.LAST_AREA, (childLM == lastLM));
            childLM.addAreas(inlinePosIter, lc);
            lc.setLeadingSpace(lc.getTrailingSpace());
            lc.setTrailingSpace(new SpaceSpecifier(false));
        }

        // if display-align is distribute, add space after
        if (context.getSpaceAfter() > 0
                && (!context.isLastArea() || !isLastPosition)) {
            lineArea.setBPD(lineArea.getBPD() + context.getSpaceAfter());
        }
        lineArea.finish();
        if (lineArea.getBidiLevel() >= 0) {
            BidiResolver.reorder(lineArea);
        }
        parentLayoutManager.addChildArea(lineArea);
    }

    /**
     * Add a line with block content
     * @param context the context for adding areas
     * @param pos the position for which the line is generated
     * @param isLastPosition true if this is the last position of this LM
     */
    private void addBlockArea(LayoutContext context, Position pos, boolean isLastPosition) {
        /* Nested block-level content;
         * go down the LM stack again;
         * "unwrap" the positions and put the child positions in a new list.
         * The positionList must contain one area-generating position,
         * which creates one line area.
         */
        List<Position> positionList = new ArrayList<>(1);
        Position innerPosition = pos.getPosition();
        positionList.add(innerPosition);

        // do we have the last LM?
        LayoutManager lastLM = null;
        if (isLastPosition) {
            lastLM = innerPosition.getLM();
        }

        LineArea lineArea = new LineArea();
        lineArea.setChangeBarList(getChangeBarList());
        setCurrentArea(lineArea);
        LayoutContext lc = LayoutContext.newInstance();
        lc.setAlignmentContext(alignmentContext);
        setChildContext(lc);

        PositionIterator childPosIter = new PositionIterator(positionList.listIterator());
        LayoutContext blocklc = LayoutContext.offspringOf(context);
        blocklc.setLeadingSpace(new SpaceSpecifier(true));
        blocklc.setTrailingSpace(new SpaceSpecifier(false));
        blocklc.setFlags(LayoutContext.RESOLVE_LEADING_SPACE, true);
        LayoutManager childLM;
        while ((childLM = childPosIter.getNextChildLM()) != null) {
            // set last area flag
            blocklc.setFlags(LayoutContext.LAST_AREA,
                             (context.isLastArea() && childLM == lastLM));
            blocklc.setStackLimitBP(context.getStackLimitBP());
            // Add the line areas to Area
            childLM.addAreas(childPosIter, blocklc);
            blocklc.setLeadingSpace(blocklc.getTrailingSpace());
            blocklc.setTrailingSpace(new SpaceSpecifier(false));
        }
        lineArea.updateExtentsFromChildren();
        if (lineArea.getBidiLevel() >= 0) {
            BidiResolver.reorder(lineArea);
        }
        parentLayoutManager.addChildArea(lineArea);
    }

    /** {@inheritDoc} */
    @Override
    public void addChildArea(Area childArea) {
        // Make sure childArea is inline area
        if (childArea instanceof InlineArea) {
            Area parent = getCurrentArea();
            if (getContext().resolveLeadingSpace()) {
                addSpace(parent, getContext().getLeadingSpace().resolve(false),
                        getContext().getSpaceAdjust());
            }
            parent.addChildArea(childArea);
        }
    }

    // --------- Property Resolution related functions --------- //

    /** {@inheritDoc} */
    @Override
    public boolean getGeneratesBlockArea() {
        return true;
    }

    /** {@inheritDoc} */
    @Override
    public boolean getGeneratesLineArea() {
        return true;
    }

    /** {@inheritDoc} */
    @Override
    public boolean isRestartable() {
        return true;
    }

    /**
     * Whether this LM can handle horizontal overflow error messages (only a BlockContainerLayoutManager can).
     * @param milliPoints horizontal overflow
     * @return true if handled by a BlockContainerLayoutManager
     */
    public boolean handleOverflow(int milliPoints) {
        if (getParent() instanceof BlockLayoutManager) {
            return ((BlockLayoutManager) getParent()).handleOverflow(milliPoints);
        }
        return false;
    }
}
