<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright © 2026, Oracle and/or its affiliates. -->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.docx4j</groupId>
		<artifactId>docx4j-parent</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>docx4j-xjc-copy</artifactId>
	<packaging>jar</packaging>
	<name>docx4j-xjc-copy</name>
	<description>XJC plugin to generate fast deep copy methods that handle parent pointers</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-xjc</artifactId>
			<version>4.0.6</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.jvnet.jaxb</groupId>
			<artifactId>jaxb-plugins-runtime</artifactId>
			<version>4.0.12</version>
		</dependency>
	</dependencies>

</project>
