/*
 *  Copyright 2016, Plutext Pty Ltd.
 *
 *  This file is part of docx4j.

    docx4j is licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

 */
package org.docx4j.dsig.crypt;

import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.imageio.ImageIO;

import java.util.Base64;
import org.docx4j.org.capaxit.imagegenerator.Margin;
import org.docx4j.org.capaxit.imagegenerator.TextImage;
import org.docx4j.org.capaxit.imagegenerator.imageexporter.ImageType;
import org.docx4j.org.capaxit.imagegenerator.imageexporter.ImageWriter;
import org.docx4j.org.capaxit.imagegenerator.imageexporter.ImageWriterFactory;
import org.docx4j.org.capaxit.imagegenerator.impl.TextImageImpl;
import org.docx4j.vml.officedrawing.CTSignatureLine;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.docx4j.dsig.DigitalSignatureException;
import org.docx4j.org.etsi.uri.x01903.v13.SignatureProductionPlaceType;

public class SignatureDetail {
	
	private static Logger LOG = LoggerFactory.getLogger(SignatureDetail.class);	
	
	PrivateKeyEntry privateKey;	// mandatory
	  /**
	  * @return the private key
	  */
	 public PrivateKey getKey() {
	     return this.privateKey.getPrivateKey();
	 }

	CTSignatureLine signatureLine; // optional
	public CTSignatureLine getSignatureLine() {
		return signatureLine;
	}

	String signatureText; 
	public String getSignatureText() {
		return signatureText;
	}

	byte[] signatureImage; 
	public byte[] getSignatureImage() {
		return signatureImage;
	}
	
	byte[] validSigLnImg; 
	public String getValidSigLnImgBase64() {
		
		if (validSigLnImg==null) {
			return null;
		} else {
			return base64encode( validSigLnImg );
				
		}
	}
	
	private String base64encode(byte[] bytes) {
		try {
			return new String(Base64.getEncoder().encode( bytes ), "UTF-8");
		} catch (UnsupportedEncodingException e) {
			throw new RuntimeException(e);
		}				
	}
	
	private String invalidMessage = "Invalid signature";
	


	/**
	 * Override the default "Invalid signature" text which is used
	 * where invalidSigLnImg has not been set (and so is autogenerated) by Docx4j).
	 * 
	 * @param invalidMessage
	 */
	public void setInvalidMessage(String invalidMessage) {
		this.invalidMessage = invalidMessage;
	}

	String invalidSigLnImg; 
	public String getInvalidSigLnImg() throws IOException, DigitalSignatureException {
		
		if (invalidSigLnImg==null) {
			
			// sniff validSigLnImg to make sure it is a PNG
			if (//validSigLnImg[0]==
					 validSigLnImg[1]=='P'
					&& validSigLnImg[2]=='N'
					&& validSigLnImg[3]=='G') {

				LOG.debug("generating invalidSigLnImg from validSigLnImg png ");
				
			} else {
				LOG.warn("validSigLnImg is not a PNG");
				throw new DigitalSignatureException("can't generate invalidSigLnImg");
			}
			
			
		    Image sigBlockImage = ImageIO.read(new ByteArrayInputStream(validSigLnImg)); // awt and javax.imageio
		    byte[] invalid = createInvalidSigLnImg( sigBlockImage,  invalidMessage);
		    return base64encode( invalid );
		}
		
		return invalidSigLnImg;
	}
	/**
	 * A base64 encoded image (Word uses EMF, but PNG tested ok with Word 2010), 
	 * displayed in the document if the signature is invalid; made up of the signature line plus the signature,
	 * plus red text saying it is invalid.
	 * 
	 * If null, can be generated from validSigLnImg, provided that is a png
	 * 
	 * @param validSigLnImg
	 */
	public void setInvalidSigLnImg(String invalidSigLnImg) {
		this.invalidSigLnImg = invalidSigLnImg;
	}
	
	private float pointsToPixels(float pt) {
		return pt * 96 / 72;
	}

	private byte[] createInvalidSigLnImg(Image sigBlockImage, String label) throws IOException {

		ByteArrayOutputStream baos = null;
		try {

			// For now, same dimensions as WordMLPictHelper, namely 
			// "width:191.7pt;height:96.3pt"
			// pixels = point * 96 / 72

			int imageWidthPx = (int) Math.round(pointsToPixels(191.7f));
			int imageHeightPx = (int) Math.round(pointsToPixels(96.3f));
			
			TextImage testImage = new TextImageImpl(imageWidthPx,
					imageHeightPx, new Margin(0, -5));

			testImage.write(sigBlockImage, 0, 0);

			//testImage.setTextAligment(Alignment.CENTER);
			testImage.withColor(Color.RED);
			testImage.write(label, 10);

			// 5. Write the image as a png to a file
			ImageWriter imageWriter = ImageWriterFactory
					.getImageWriter(ImageType.PNG);
			baos = new ByteArrayOutputStream();
			imageWriter.writeImageToOutputStream(testImage, baos);
			return baos.toByteArray();

		} finally {
			baos.close();
		}

	}	
	
	
	

	String signatureComments;
	/**
	 * In the Office UI, this is "purpose"
	 * @param signatureComments
	 */
	public void setSignatureComments(String signatureComments) {
		this.signatureComments = signatureComments;
	}


	public String getSignatureComments() {
		return signatureComments;
	}

	
	private SignatureDetail() {}
	
	public SignatureDetail(PrivateKeyEntry privateKey) {
		
		this.privateKey = privateKey;
	}

	/**
	 * Configure the visual signature, in prep for signing.  
	 * 
	 * @param signatureLine
	 * @param validSigLnImg   the image (Word uses EMF, but PNG tested ok with Word 2010
	 * and MUST be used since we can't manipulate an EMF, yet), 
	 * displayed in the document; should be the signature line plus the signature.
	 * @param signatureText
	 */
	public void setVisualSignature(CTSignatureLine signatureLine, byte[] validSigLnImg, String signatureText) {
		
		this.signatureLine = signatureLine;
		this.signatureText = signatureText; 
		
		this.validSigLnImg = validSigLnImg;
		
		this.signatureImage = null; 
	}

	/**
	 * Configure the visual signature, in prep for signing.  
	 * 
	 * @param signatureLine
	 * @param validSigLnImg   the image (Word uses EMF, but PNG tested ok with Word 2010
	 * and MUST be used since we can't manipulate an EMF, yet), 
	 * displayed in the document; should be the signature line plus the signature.
	 * @param signatureImage  the signature itself (not actually displayed), but stored
	 */
	public void setVisualSignature(CTSignatureLine signatureLine,
			byte[] validSigLnImg, byte[] signatureImage) {

		// Word 2010 doesn't complain if you have both signature text and image,
		// but the image trumps the text (ie it doesn't display it).
		// So our API design only allows one or the other.

		this.signatureLine = signatureLine;
		this.signatureText = null;

		this.validSigLnImg = validSigLnImg;

		this.signatureImage = signatureImage;
	}

	/**
	 * @return the certificate chain, index 0 is usually the certificate
	 *         matching the private key
	 */
	public List<X509Certificate> getSigningCertificateChain() {
		
		// The whole chain, so that (with SignatureConfig.includeEntireCertificateChain) a
		// validator gets the intermediates.  Until 2026 this was the signer alone.
		List<X509Certificate> chain = new ArrayList<X509Certificate>();
		for (Certificate c : this.privateKey.getCertificateChain()) {
			chain.add((X509Certificate) c);
		}
		return chain;
	}

	/**
	 * <xd:SignerRole> <xd:ClaimedRoles> <xd:ClaimedRole>kkk</xd:ClaimedRole>
	 * </xd:ClaimedRoles> </xd:SignerRole>
	 */
	private String xadesRole = null;

	/**
	 * @return the xades role element. If <code>null</code> the claimed role
	 *         element is omitted. Defaults to <code>null</code>
	 */
	public String getXadesRole() {
		return xadesRole;
	}

	/**
	 * @param xadesRole
	 *            the xades role element. If <code>null</code> the claimed role
	 *            element is omitted.
	 */
	public void setXadesRole(String xadesRole) {
		this.xadesRole = xadesRole;
	}

	/*
          <xd:SignatureProductionPlace>
            <xd:City></xd:City>
            <xd:StateOrProvince></xd:StateOrProvince>
            <xd:PostalCode></xd:PostalCode>
            <xd:CountryName></xd:CountryName>
          </xd:SignatureProductionPlace>
	 */
			
	private SignatureProductionPlaceType signatureProductionPlace;

	public SignatureProductionPlaceType getSignatureProductionPlace() {
		return signatureProductionPlace;
	}

	public void setSignatureProductionPlace(
			SignatureProductionPlaceType signatureProductionPlace) {
		this.signatureProductionPlace = signatureProductionPlace;
	}

	/*
        <xd:SignedDataObjectProperties>
          <xd:CommitmentTypeIndication>
            <xd:CommitmentTypeId>
              <xd:Identifier>http://uri.etsi.org/01903/v1.2.2#ProofOfOrigin</xd:Identifier>
              <xd:Description>Created and approved this document</xd:Description>
            </xd:CommitmentTypeId>
	 */
	private CommitmentType commitmentType;
	public CommitmentType getCommitmentType() {
		return commitmentType;
	}

	public void setCommitmentType(CommitmentType commitmentType) {
		this.commitmentType = commitmentType;
	}
}
