/*
 *  Copyright 2014, Plutext Pty Ltd.
 *
 *  This file is part of docx4j.

    docx4j is licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.

    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

 */
package org.docx4j.model.listnumbering;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;

import junit.framework.Assert;

import org.docx4j.XmlUtils;
import org.docx4j.jaxb.Context;
import org.docx4j.openpackaging.packages.WordprocessingMLPackage;
import org.docx4j.openpackaging.parts.WordprocessingML.MainDocumentPart;
import org.docx4j.openpackaging.parts.WordprocessingML.NumberingDefinitionsPart;
import org.docx4j.wml.Numbering;
import org.docx4j.wml.P;
import org.docx4j.wml.PPr;
import org.docx4j.wml.PPrBase;
import org.docx4j.wml.R;
import org.docx4j.wml.Styles;
import org.docx4j.wml.Text;
import org.junit.Test;

public class NumberingSample1Test {

	private static org.docx4j.wml.ObjectFactory wmlObjectFactory = Context.getWmlObjectFactory();

	@Test
	public void testNumbering() throws Exception {
		
		WordprocessingMLPackage wordMLPackage = createPkg();
		
		MainDocumentPart mdp = wordMLPackage.getMainDocumentPart();

		P p = createNumberedP("ChapterLevel1", 12, 0);
		mdp.getContent().add(p);
		Assert.assertEquals("1", Emulator.getNumber(wordMLPackage, p.getPPr()).getNumString());
		
		//System.out.println(Emulator.getNumber(wordMLPackage, p.getPPr()).getNumString());
		
		p = createNumberedP("ChapterLevel2", 6, 1);
		mdp.getContent().add(p);
		Assert.assertEquals("1.1", Emulator.getNumber(wordMLPackage, p.getPPr()).getNumString());
		
		p = createNumberedP("ChapterLevel2", 6, 1);
		mdp.getContent().add(p);
		Assert.assertEquals("1.2", Emulator.getNumber(wordMLPackage, p.getPPr()).getNumString());

		p = createNumberedP("ChapterLevel3", 6, 2);
		mdp.getContent().add(p);
		Assert.assertEquals("1.2.1", Emulator.getNumber(wordMLPackage, p.getPPr()).getNumString());
		
		p = createNumberedP("ChapterLevel1", -1, -1); // no numPr
		mdp.getContent().add(p);
		Assert.assertEquals("2", Emulator.getNumber(wordMLPackage, p.getPPr()).getNumString());
		
	}

	protected P createNumberedP(String style, int numId, int ilvl) {
		
		P p = wmlObjectFactory.createP(); 
		    // Create object for pPr
		    PPr ppr = wmlObjectFactory.createPPr(); 
		    p.setPPr(ppr); 
		    
		    if (numId>-1) {
		        // Create object for numPr
		        PPrBase.NumPr pprbasenumpr = wmlObjectFactory.createPPrBaseNumPr(); 
		        ppr.setNumPr(pprbasenumpr); 
		            // Create object for ilvl
		            PPrBase.NumPr.Ilvl pprbasenumprilvl = wmlObjectFactory.createPPrBaseNumPrIlvl(); 
		            pprbasenumpr.setIlvl(pprbasenumprilvl); 
		                pprbasenumprilvl.setVal( BigInteger.valueOf( ilvl) ); 
		            // Create object for numId
		            PPrBase.NumPr.NumId pprbasenumprnumid = wmlObjectFactory.createPPrBaseNumPrNumId(); 
		            pprbasenumpr.setNumId(pprbasenumprnumid); 
		                pprbasenumprnumid.setVal( BigInteger.valueOf( numId) ); 
		    }
		        // Create object for pStyle
		        PPrBase.PStyle pprbasepstyle = wmlObjectFactory.createPPrBasePStyle(); 
		        ppr.setPStyle(pprbasepstyle); 
		            pprbasepstyle.setVal( style); 
		    // Create object for r
		    R r = wmlObjectFactory.createR(); 
		    p.getContent().add( r); 
		        // Create object for t (wrapped in JAXBElement) 
		        Text text = wmlObjectFactory.createText(); 
		        JAXBElement<org.docx4j.wml.Text> textWrapped = wmlObjectFactory.createRT(text); 
		        r.getContent().add( textWrapped); 
		            text.setValue( style + "; list " + numId + ", ilvl " + ilvl); 

		return p;
		}
	
	protected P createUnnumberedP() {
		
		P p = wmlObjectFactory.createP(); 
		    R r = wmlObjectFactory.createR(); 
		    p.getContent().add( r); 
		        // Create object for t (wrapped in JAXBElement) 
		        Text text = wmlObjectFactory.createText(); 
		        JAXBElement<org.docx4j.wml.Text> textWrapped = wmlObjectFactory.createRT(text); 
		        r.getContent().add( textWrapped); 
		            text.setValue( "UnnumberedP"); 

		return p;
		}	
	
	protected WordprocessingMLPackage createPkg() throws Exception {

		WordprocessingMLPackage wordMLPackage = WordprocessingMLPackage.createPackage();
		
		NumberingDefinitionsPart ndp = new NumberingDefinitionsPart();
		ndp.setContents((Numbering)XmlUtils.unmarshalString(numberingXml));
		
		wordMLPackage.getMainDocumentPart().addTargetPart(ndp);
		
		wordMLPackage.getMainDocumentPart().getStyleDefinitionsPart().setJaxbElement((Styles)XmlUtils.unmarshalString(stylesXml));
		
		return wordMLPackage;
	}
	

	private static final String stylesXml = "<w:styles mc:Ignorable=\"w14 w15\" xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\">"
            + "<w:docDefaults>"
                  + "<w:rPrDefault>"
                        + "<w:rPr>"
                              + "<w:rFonts w:asciiTheme=\"minorHAnsi\" w:cstheme=\"minorBidi\" w:eastAsiaTheme=\"minorHAnsi\" w:hAnsiTheme=\"minorHAnsi\"/>"
                              + "<w:sz w:val=\"22\"/>"
                              + "<w:szCs w:val=\"22\"/>"
                              + "<w:lang w:bidi=\"ar-SA\" w:eastAsia=\"en-US\" w:val=\"en-US\"/>"
                        + "</w:rPr>"
                  + "</w:rPrDefault>"
                  + "<w:pPrDefault>"
                        + "<w:pPr>"
                              + "<w:spacing w:after=\"200\" w:line=\"276\" w:lineRule=\"auto\"/>"
                        + "</w:pPr>"
                  + "</w:pPrDefault>"
            + "</w:docDefaults>"
            + "<w:style w:default=\"1\" w:styleId=\"Standard\" w:type=\"paragraph\">"
                  + "<w:name w:val=\"Normal\"/>"
                  + "<w:qFormat/>"
                  + "<w:rsid w:val=\"00A65E0E\"/>"
                  + "<w:rPr>"
                        + "<w:noProof/>"
                        + "<w:sz w:val=\"24\"/>"
                  + "</w:rPr>"
            + "</w:style>"
            + "<w:style w:styleId=\"berschrift1\" w:type=\"paragraph\">"
                  + "<w:name w:val=\"heading 1\"/>"
                  + "<w:basedOn w:val=\"Standard\"/>"
                  + "<w:next w:val=\"Standard\"/>"
                  + "<w:link w:val=\"berschrift1Zchn\"/>"
                  + "<w:uiPriority w:val=\"9\"/>"
                  + "<w:qFormat/>"
                  + "<w:rsid w:val=\"00A65E0E\"/>"
                  + "<w:pPr>"
                        + "<w:keepNext/>"
                        + "<w:keepLines/>"
                        + "<w:numPr>"
                              + "<w:numId w:val=\"8\"/>"
                        + "</w:numPr>"
                        + "<w:spacing w:after=\"0\" w:before=\"240\"/>"
                        + "<w:outlineLvl w:val=\"0\"/>"
                  + "</w:pPr>"
                  + "<w:rPr>"
                        + "<w:rFonts w:asciiTheme=\"majorHAnsi\" w:cstheme=\"majorBidi\" w:eastAsiaTheme=\"majorEastAsia\" w:hAnsiTheme=\"majorHAnsi\"/>"
                        + "<w:color w:themeColor=\"accent1\" w:themeShade=\"BF\" w:val=\"2E74B5\"/>"
                        + "<w:sz w:val=\"32\"/>"
                        + "<w:szCs w:val=\"32\"/>"
                  + "</w:rPr>"
            + "</w:style>"
            + "<w:style w:styleId=\"berschrift2\" w:type=\"paragraph\">"
                  + "<w:name w:val=\"heading 2\"/>"
                  + "<w:basedOn w:val=\"Standard\"/>"
                  + "<w:next w:val=\"Standard\"/>"
                  + "<w:link w:val=\"berschrift2Zchn\"/>"
                  + "<w:uiPriority w:val=\"9\"/>"
                  + "<w:unhideWhenUsed/>"
                  + "<w:qFormat/>"
                  + "<w:rsid w:val=\"00A65E0E\"/>"
                  + "<w:pPr>"
                        + "<w:keepNext/>"
                        + "<w:keepLines/>"
                        + "<w:numPr>"
                              + "<w:ilvl w:val=\"1\"/>"
                              + "<w:numId w:val=\"8\"/>"
                        + "</w:numPr>"
                        + "<w:spacing w:after=\"0\" w:before=\"40\"/>"
                        + "<w:outlineLvl w:val=\"1\"/>"
                  + "</w:pPr>"
                  + "<w:rPr>"
                        + "<w:rFonts w:asciiTheme=\"majorHAnsi\" w:cstheme=\"majorBidi\" w:eastAsiaTheme=\"majorEastAsia\" w:hAnsiTheme=\"majorHAnsi\"/>"
                        + "<w:color w:themeColor=\"accent1\" w:themeShade=\"BF\" w:val=\"2E74B5\"/>"
                        + "<w:sz w:val=\"26\"/>"
                        + "<w:szCs w:val=\"26\"/>"
                  + "</w:rPr>"
            + "</w:style>"
            + "<w:style w:styleId=\"berschrift3\" w:type=\"paragraph\">"
                  + "<w:name w:val=\"heading 3\"/>"
                  + "<w:basedOn w:val=\"Standard\"/>"
                  + "<w:next w:val=\"Standard\"/>"
                  + "<w:link w:val=\"berschrift3Zchn\"/>"
                  + "<w:uiPriority w:val=\"9\"/>"
                  + "<w:unhideWhenUsed/>"
                  + "<w:qFormat/>"
                  + "<w:rsid w:val=\"00A65E0E\"/>"
                  + "<w:pPr>"
                        + "<w:keepNext/>"
                        + "<w:keepLines/>"
                        + "<w:numPr>"
                              + "<w:ilvl w:val=\"2\"/>"
                              + "<w:numId w:val=\"8\"/>"
                        + "</w:numPr>"
                        + "<w:spacing w:after=\"0\" w:before=\"40\"/>"
                        + "<w:outlineLvl w:val=\"2\"/>"
                  + "</w:pPr>"
                  + "<w:rPr>"
                        + "<w:rFonts w:asciiTheme=\"majorHAnsi\" w:cstheme=\"majorBidi\" w:eastAsiaTheme=\"majorEastAsia\" w:hAnsiTheme=\"majorHAnsi\"/>"
                        + "<w:color w:themeColor=\"accent1\" w:themeShade=\"7F\" w:val=\"1F4D78\"/>"
                        + "<w:szCs w:val=\"24\"/>"
                  + "</w:rPr>"
            + "</w:style>"
            + "<w:style w:customStyle=\"1\" w:styleId=\"ChapterLevel1\" w:type=\"paragraph\">"
                  + "<w:name w:val=\"ChapterLevel1\"/>"
                  + "<w:basedOn w:val=\"berschrift1\"/>"
                  + "<w:next w:val=\"Standard\"/>"
                  + "<w:qFormat/>"
                  + "<w:rsid w:val=\"00A65E0E\"/>"
                  + "<w:pPr>"
                        + "<w:spacing w:after=\"200\" w:before=\"480\"/>"
                  + "</w:pPr>"
                  + "<w:rPr>"
                        + "<w:rFonts w:asciiTheme=\"minorHAnsi\" w:hAnsiTheme=\"minorHAnsi\"/>"
                        + "<w:b/>"
                        + "<w:color w:val=\"002D61\"/>"
                        + "<w:sz w:val=\"40\"/>"
                        + "<w:szCs w:val=\"28\"/>"
                        + "<w:lang w:val=\"de-DE\"/>"
                  + "</w:rPr>"
            + "</w:style>"
            + "<w:style w:customStyle=\"1\" w:styleId=\"ChapterLevel2\" w:type=\"paragraph\">"
                  + "<w:name w:val=\"ChapterLevel2\"/>"
                  + "<w:basedOn w:val=\"berschrift2\"/>"
                  + "<w:qFormat/>"
                  + "<w:rsid w:val=\"00A65E0E\"/>"
                  + "<w:pPr>"
                        + "<w:spacing w:after=\"200\" w:before=\"240\"/>"
                        + "<w:ind w:hanging=\"578\" w:left=\"578\"/>"
                  + "</w:pPr>"
                  + "<w:rPr>"
                        + "<w:rFonts w:asciiTheme=\"minorHAnsi\" w:hAnsiTheme=\"minorHAnsi\"/>"
                        + "<w:bCs/>"
                        + "<w:color w:val=\"002D61\"/>"
                        + "<w:sz w:val=\"36\"/>"
                        + "<w:lang w:val=\"de-DE\"/>"
                  + "</w:rPr>"
            + "</w:style>"
            + "<w:style w:customStyle=\"1\" w:styleId=\"ChapterLevel3\" w:type=\"paragraph\">"
                  + "<w:name w:val=\"ChapterLevel3\"/>"
                  + "<w:basedOn w:val=\"berschrift3\"/>"
                  + "<w:qFormat/>"
                  + "<w:rsid w:val=\"0023411C\"/>"
                  + "<w:pPr>"
                        + "<w:spacing w:before=\"240\"/>"
                  + "</w:pPr>"
                  + "<w:rPr>"
                        + "<w:rFonts w:asciiTheme=\"minorHAnsi\" w:hAnsiTheme=\"minorHAnsi\"/>"
                        + "<w:bCs/>"
                        + "<w:color w:val=\"002D61\"/>"
                        + "<w:sz w:val=\"36\"/>"
                        + "<w:szCs w:val=\"22\"/>"
                  + "</w:rPr>"
            + "</w:style>"

      + "</w:styles>";
	private static final String numberingXml = "<w:numbering mc:Ignorable=\"w14 w15 wp14\" xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:mc=\"http://schemas.openxmlformats.org/markup-compatibility/2006\">"
            + "<w:abstractNum w:abstractNumId=\"0\">"
                  + "<w:nsid w:val=\"FFFFFF7C\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"B2B8B700\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"1492\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"1492\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"1\">"
                  + "<w:nsid w:val=\"FFFFFF7D\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"EDD25514\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"1209\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"1209\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"2\">"
                  + "<w:nsid w:val=\"FFFFFF7E\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"8A1274A6\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"926\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"926\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"3\">"
                  + "<w:nsid w:val=\"FFFFFF7F\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"049AF484\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"643\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"643\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"4\">"
                  + "<w:nsid w:val=\"FFFFFF80\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"7F4298A4\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"•\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"1492\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"1492\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Symbol\" w:hAnsi=\"Symbol\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"5\">"
                  + "<w:nsid w:val=\"FFFFFF81\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"416E674E\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"•\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"1209\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"1209\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Symbol\" w:hAnsi=\"Symbol\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"6\">"
                  + "<w:nsid w:val=\"FFFFFF82\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"C1DCAEB8\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"•\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"926\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"926\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Symbol\" w:hAnsi=\"Symbol\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"7\">"
                  + "<w:nsid w:val=\"FFFFFF83\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"32263CA4\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"•\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"643\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"643\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Symbol\" w:hAnsi=\"Symbol\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"8\">"
                  + "<w:nsid w:val=\"FFFFFF88\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"511E5FE8\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"360\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"360\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"9\">"
                  + "<w:nsid w:val=\"FFFFFF89\"/>"
                  + "<w:multiLevelType w:val=\"singleLevel\"/>"
                  + "<w:tmpl w:val=\"9D9E59E6\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"•\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:tabs>"
                                    + "<w:tab w:pos=\"360\" w:val=\"num\"/>"
                              + "</w:tabs>"
                              + "<w:ind w:hanging=\"360\" w:left=\"360\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Symbol\" w:hAnsi=\"Symbol\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"10\">"
                  + "<w:nsid w:val=\"281E4A41\"/>"
                  + "<w:multiLevelType w:val=\"multilevel\"/>"
                  + "<w:tmpl w:val=\"04070025\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"432\" w:left=\"432\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"1\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"576\" w:left=\"576\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"2\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"720\" w:left=\"720\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"3\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"864\" w:left=\"864\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"4\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1008\" w:left=\"1008\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"5\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5.%6\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1152\" w:left=\"1152\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"6\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5.%6.%7\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1296\" w:left=\"1296\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"7\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5.%6.%7.%8\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1440\" w:left=\"1440\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"8\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5.%6.%7.%8.%9\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1584\" w:left=\"1584\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"11\">"
                  + "<w:nsid w:val=\"48E650EA\"/>"
                  + "<w:multiLevelType w:val=\"multilevel\"/>"
                  + "<w:tmpl w:val=\"DA626B22\"/>"
                  + "<w:styleLink w:val=\"UnorderedList\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"•\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"1287\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Symbol\" w:hAnsi=\"Symbol\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"1\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"o\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"2007\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Courier New\" w:cs=\"Courier New\" w:hAnsi=\"Courier New\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"2\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"2727\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Wingdings\" w:hAnsi=\"Wingdings\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"3\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"•\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"3447\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Symbol\" w:hAnsi=\"Symbol\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"4\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"o\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"4167\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Courier New\" w:cs=\"Courier New\" w:hAnsi=\"Courier New\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"5\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"4887\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Wingdings\" w:hAnsi=\"Wingdings\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"6\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"•\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"5607\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Symbol\" w:hAnsi=\"Symbol\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"7\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"o\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"6327\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Courier New\" w:cs=\"Courier New\" w:hAnsi=\"Courier New\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"8\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"bullet\"/>"
                        + "<w:lvlText w:val=\"\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"7047\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:ascii=\"Wingdings\" w:hAnsi=\"Wingdings\" w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"12\">"
                  + "<w:nsid w:val=\"52AF3F57\"/>"
                  + "<w:multiLevelType w:val=\"multilevel\"/>"
                  + "<w:tmpl w:val=\"C524B0F8\"/>"
                  + "<w:styleLink w:val=\"OrderedList\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1)\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"360\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"1\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"lowerLetter\"/>"
                        + "<w:lvlText w:val=\"%2)\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"720\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"2\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"lowerRoman\"/>"
                        + "<w:lvlText w:val=\"%3)\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"1080\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"3\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"(%4)\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"1440\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"4\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"lowerLetter\"/>"
                        + "<w:lvlText w:val=\"(%5)\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"1800\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"5\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"lowerRoman\"/>"
                        + "<w:lvlText w:val=\"(%6)\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"2160\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"6\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%7.\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"2520\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"7\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"lowerLetter\"/>"
                        + "<w:lvlText w:val=\"%8.\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"2880\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"8\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"lowerRoman\"/>"
                        + "<w:lvlText w:val=\"%9.\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"360\" w:left=\"3240\"/>"
                        + "</w:pPr>"
                        + "<w:rPr>"
                              + "<w:rFonts w:hint=\"default\"/>"
                        + "</w:rPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"13\">"
                  + "<w:nsid w:val=\"57DC56E5\"/>"
                  + "<w:multiLevelType w:val=\"multilevel\"/>"
                  + "<w:tmpl w:val=\"DA626B22\"/>"
                  + "<w:numStyleLink w:val=\"UnorderedList\"/>"
            + "</w:abstractNum>"
            + "<w:abstractNum w:abstractNumId=\"14\">"
                  + "<w:nsid w:val=\"63904EC4\"/>"
                  + "<w:multiLevelType w:val=\"multilevel\"/>"
                  + "<w:tmpl w:val=\"DAFE0122\"/>"
                  + "<w:lvl w:ilvl=\"0\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:pStyle w:val=\"berschrift1\"/>"
                        + "<w:lvlText w:val=\"%1\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"432\" w:left=\"432\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"1\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:pStyle w:val=\"berschrift2\"/>"
                        + "<w:lvlText w:val=\"%1.%2\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"576\" w:left=\"576\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"2\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:pStyle w:val=\"berschrift3\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"720\" w:left=\"720\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"3\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:pStyle w:val=\"berschrift4\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"864\" w:left=\"864\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"4\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1008\" w:left=\"1008\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"5\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5.%6\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1152\" w:left=\"1152\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"6\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5.%6.%7\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1296\" w:left=\"1296\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"7\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5.%6.%7.%8\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1440\" w:left=\"1440\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
                  + "<w:lvl w:ilvl=\"8\">"
                        + "<w:start w:val=\"1\"/>"
                        + "<w:numFmt w:val=\"decimal\"/>"
                        + "<w:lvlText w:val=\"%1.%2.%3.%4.%5.%6.%7.%8.%9\"/>"
                        + "<w:lvlJc w:val=\"left\"/>"
                        + "<w:pPr>"
                              + "<w:ind w:hanging=\"1584\" w:left=\"1584\"/>"
                        + "</w:pPr>"
                  + "</w:lvl>"
            + "</w:abstractNum>"
            + "<w:num w:numId=\"1\">"
                  + "<w:abstractNumId w:val=\"9\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"2\">"
                  + "<w:abstractNumId w:val=\"7\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"3\">"
                  + "<w:abstractNumId w:val=\"6\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"4\">"
                  + "<w:abstractNumId w:val=\"5\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"5\">"
                  + "<w:abstractNumId w:val=\"4\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"6\">"
                  + "<w:abstractNumId w:val=\"14\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"7\">"
                  + "<w:abstractNumId w:val=\"14\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"8\">"
                  + "<w:abstractNumId w:val=\"14\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"9\">"
                  + "<w:abstractNumId w:val=\"12\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"10\">"
                  + "<w:abstractNumId w:val=\"11\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"11\">"
                  + "<w:abstractNumId w:val=\"13\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"12\">"
                  + "<w:abstractNumId w:val=\"10\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"13\">"
                  + "<w:abstractNumId w:val=\"8\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"14\">"
                  + "<w:abstractNumId w:val=\"3\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"15\">"
                  + "<w:abstractNumId w:val=\"2\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"16\">"
                  + "<w:abstractNumId w:val=\"1\"/>"
            + "</w:num>"
            + "<w:num w:numId=\"17\">"
                  + "<w:abstractNumId w:val=\"0\"/>"
            + "</w:num>"
      + "</w:numbering>"
;	

}
