<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="qualified"
	blockDefault="#all"
	xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb"
	xmlns:xjc="https://jakarta.ee/xml/ns/jaxb/xjc" jaxb:version="3.0">
	
	<!-- sh ~/git/docx4j/xjc/jaxb-ri/bin/xjc.sh  ROOT.xsd -d tmp  -no-header -target 3.0 
	
		wc -l gives 2512
	-->
	
	<!-- pptx__ROOT.xsd generates a superset of wml.xsd|dml_ROOT -->
	<xsd:import id="pptx" namespace="http://schemas.openxmlformats.org/presentationml/2006/main" schemaLocation="pptx/pptx__ROOT.xsd"/>
	<xsd:import id="w16cid" namespace="http://schemas.microsoft.com/office/word/2016/wordml/cid" schemaLocation="wml/w16cid.xsd"/>
	<xsd:import id="w15symex" namespace="http://schemas.microsoft.com/office/word/2015/wordml/symex" schemaLocation="wml/w15symex.xsd"/>


	<!-- sml_root.xsd generates a superset of wml.xsd|dml_ROOT; a different superset to pptx_ROOT.xsd -->
	<xsd:import id="sml" namespace="http://schemas.openxmlformats.org/spreadsheetml/2006/main" schemaLocation="sml/sml_root.xsd"/>
    <xsd:import id="ida" namespace="http://schemas.microsoft.com/office/excel/2006/main" schemaLocation="offmacro/office-excel-2006-main.xsd"/>
    <xsd:import id="sd" namespace="http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing" schemaLocation="odrawxml/spreadsheetDrawing2010.xsd"/>
    <xsd:import id="idb" namespace="http://schemas.microsoft.com/office/excel/2008/2/main" schemaLocation="offmacro/office-excel-2008-2-main.xsd"/>
    
    <xsd:import id="vml" namespace="foo" schemaLocation="vml/vml__ROOT.xsd"/>
    
    <xsd:import id="wx" namespace="http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11" schemaLocation="webextensions/taskpanes_2010_11.xsd"/>
    
	<!-- the below could be generated separately if desired, except that they also generate the 7 classes in org/docx4j/sharedtypes -->
	
    <xsd:import id="id1" namespace="http://schemas.openxmlformats.org/officeDocument/2006/bibliography" schemaLocation="shared/shared-bibliography.xsd"/>
    <xsd:import id="id2" namespace="http://schemas.openxmlformats.org/officeDocument/2006/customXml" schemaLocation="customXmlProperties/shared-customxmlprops.xsd"/>
    <xsd:import id="id3" namespace="http://schemas.microsoft.com/‌office/‌2006/‌coverPageProps" schemaLocation="customXmlWellDefined/coverpageproperties.xsd"/>
    <xsd:import id="id4" namespace="http://schemas.microsoft.com/office/2006/encryption" schemaLocation="digSig/office-2006-encryption.xsd"/>
    <xsd:import id="id5" namespace="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" schemaLocation="docProps/opc-coreProperties.xsd"/>
    <xsd:import id="id6" namespace="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties" schemaLocation="docProps/shared-documentPropertiesCustom.xsd"/>
    <xsd:import id="id7" namespace="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" schemaLocation="docProps/shared-documentPropertiesExtended.xsd"/>
    <xsd:import id="id8" namespace="http://schemas.openxmlformats.org/package/2006/relationships" schemaLocation="relationships.xsd"/>
    <xsd:import id="id9" namespace="http://schemas.microsoft.com/office/2006/xmlPackage" schemaLocation="xmlPackage.xsd"/>
    
    
</xsd:schema>
